In [ ]:
import pandas as pd
import polars as pl
import ast
import networkx as nx
from network_creation import *

### Read old and new organizations datasets

In [43]:
old_folder = 'cleaned organizations/ok organizations/'
new_folder = 'data new'

# old df
old_1 = pd.read_csv(old_folder + 'org_geo_new_1.csv')
old_2 = pd.read_csv(old_folder + 'org_geo_new_2.csv')
old_3 = pd.read_csv(old_folder + 'org_geo_new_3.csv')
old_4 = pd.read_csv(old_folder + 'org_geo_new_4.csv')
old_5 = pd.read_csv(old_folder + 'org_geo_new_5.csv')
old_6 = pd.read_csv(old_folder + 'org_geo_new_6.csv')
old_7 = pd.read_csv(old_folder + 'org_geo_7.csv')
old_8 = pd.read_csv(old_folder + 'org_geo_8.csv')
old_9 = pd.read_csv(old_folder + 'org_9_reduced.csv')

old_df = [old_1, old_2, old_3, old_4, old_5, old_6, old_7, old_8, old_9]

# new df
new_1 = pd.read_csv(new_folder + '/cordis-fp1projects-csv/organization.csv', sep=';')
new_2 = pd.read_csv(new_folder + '/cordis-fp2projects-csv/organization.csv', sep=';')
new_3 = pd.read_csv(new_folder + '/cordis-fp3projects-csv/organization.csv', sep=';')
new_4 = pd.read_csv(new_folder + '/cordis-fp4projects-csv/organization.csv', sep=';')
new_5 = pd.read_csv(new_folder + '/cordis-fp5projects-csv/organization.csv', sep=';')
new_6 = pd.read_csv(new_folder + '/cordis-fp6projects-csv/organization_ok.csv', sep=';')
new_7 = pd.read_csv(new_folder + '/cordis-fp7projects-csv/organization.csv', sep=';')
new_8 = pd.read_csv(new_folder + '/cordis-h2020projects-csv/organization.csv', sep=';')
new_9 = pd.read_csv(new_folder + '/cordis-HORIZONprojects-csv/organization.csv', sep=';')

new_df = [new_1, new_2, new_3, new_4, new_5, new_6, new_7, new_8, new_9]

/tmp/ipykernel_2795924/570263204.py:6: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  old_2 = pd.read_csv(old_folder + 'org_geo_new_2.csv')
/tmp/ipykernel_2795924/570263204.py:11: DtypeWarning: Columns (9,21) have mixed types. Specify dtype option on import or set low_memory=False.
  old_7 = pd.read_csv(old_folder + 'org_geo_7.csv')
/tmp/ipykernel_2795924/570263204.py:21: DtypeWarning: Columns (3,7,12,18) have mixed types. Specify dtype option on import or set low_memory=False.
  new_4 = pd.read_csv(new_folder + '/cordis-fp4projects-csv/organization.csv', sep=';')
/tmp/ipykernel_2795924/570263204.py:22: DtypeWarning: Columns (3,7,12,18) have mixed types. Specify dtype option on import or set low_memory=False.
  new_5 = pd.read_csv(new_folder + '/cordis-fp5projects-csv/organization.csv', sep=';')
/tmp/ipykernel_2795924/570263204.py:23: DtypeWarning: Columns (3,12) have mixed types. Specify dtype option on import or set low_memory=False.
  new_6 = pd.read_csv(new_folder + '/cordis-fp6projects-csv/organization_ok.csv', sep=';')
/tmp/ipykernel_2795924/570263204.py:24: DtypeWarning: Columns (17,18,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  new_7 = pd.read_csv(new_folder + '/cordis-fp7projects-csv/organization.csv', sep=';')

In [44]:
# compare number of elements in old and new df

d = list(zip(old_df, new_df))

for el in d:
    print(len(el[0]), len(el[1]))

7900 7916
19054 19075
31350 31364
65418 67858
81089 81752
75274 75216
155534 140064
148841 178414
89680 115056

### Map organization with geographical info from old dataset to new dataset

In [45]:
# extract organizations

for i in range(len(old_df) - 1):
    old_df[i] = old_df[i].rename(columns={'projectRcn': 'rcn', 'projectReference': 'projectID', 'organization': 'name', 'name_x': 'name', 'city_y': 'city', 'country_y': 'country', 'country_code': 'country_code_nominatim', 'country equal' : 'match_country_org_nom'})
    old_df[i] = old_df[i][['name', 'address', 'lat', 'lon', 'bbox', 'municipality', 'village', 'town', 'city', 'country', 'county', 'state', 'state_district', 'country_code_nominatim', 'importance', 'granularity', 'city_nominatim', 'match_country_org_nom']]

df_old_tot = pd.concat(old_df, ignore_index=True)
df_old_tot['name'] = df_old_tot['name'].str.lower()

# drop duplicates to have unique names of organizations
df_drop = df_old_tot.drop_duplicates(subset=['name'], keep='first').reset_index(drop=True)
df_drop

,name,address,lat,lon,bbox,municipality,village,town,city,country,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,trinity college,"{'city': 'Dublin', 'county': 'County Dublin', ...",53.349379,-6.260559,"['53.2987342', '53.4105416', '-6.3870259', '-6...",NaN,NaN,NaN,Dublin,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"univ di roma ""la sapienza""","{'city': 'Rome', 'county': 'Roma Capitale', 'I...",41.893320,12.482932,"['41.6556417', '42.1410285', '12.2344669', '12...",NaN,NaN,NaN,Rome,Italy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,univ catholique de louvain,"{'city_district': 'Louvain-la-Neuve', 'town': ...",50.674169,4.613791,"['50.6590954', '50.6894891', '4.5956956', '4.6...",NaN,NaN,Ottignies-Louvain-la-Neuve,NaN,Belgium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,rijksuniversiteit gent,"{'city': 'Ghent', 'county': 'Gent', 'state': '...",51.053829,3.725012,"['50.9795422', '51.1888864', '3.5797616', '3.8...",NaN,NaN,NaN,Ghent,Belgium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,inst jaime almera,"{'city': 'Almeria', 'province': 'Almeria', 'IS...",36.841420,-2.462814,"['35.9376398', '37.0000125', '-3.0372135', '-2...",NaN,NaN,NaN,Almeria,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153651,clariant ag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tarragona,ES,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-07-24 17:09:30,1988813.0,13.0,associatedPartner,NaN,0.0,0,False,NaN
153652,foresight institute,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Francisco,US,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-07-24 17:09:30,1988815.0,17.0,associatedPartner,NaN,0.0,0,False,NaN
153653,oriensys srl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Strasbourg,FR,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-07-24 17:09:30,1988816.0,18.0,associatedPartner,NaN,0.0,0,False,NaN
153654,the desca foundation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dover,US,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-07-24 17:09:30,1988814.0,14.0,associatedPartner,NaN,0.0,0,False,NaN
153655,merck millipore ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cork,IE,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-07-24 17:09:30,1988812.0,12.0,associatedPartner,NaN,0.0,0,False,NaN

In [48]:
# merge new df with df of unique organizations with geographical info

merged_list = []

for i in range(len(new_df)):
    new_df[i]['name'] = new_df[i]['name'].str.lower()
    org_merged = pd.merge(new_df[i], df_drop, on='name', how='left')
    #org_merged.to_csv('data new/merged_old_new_1/merged_org_' + str(i+1) + '.csv', index=False)
    merged_list += [org_merged]
    '''org_new['country'] = org_new['country'].str.lower()
    org_new['street'] = org_new['street'].str.lower()
    org_new = org_new.rename(columns={'country': 'country_code_original'})
    org_new = org_new[['rcn', 'projectID', 'name', 'role', 'street', 'postalCode', 'city', 'region', 'country_code_original']]
    new_df[i] = org_new.drop_duplicates().reset_index(drop=True)'''

In [52]:
# extract organization with missing information about country

for i in range(len(merged_list)):
    missing = merged_list[i].drop_duplicates(subset=['name'], keep='first').reset_index(drop=True)
    missing = missing[missing['country_code_nominatim'].isna()]
    #missing.to_csv('data new/merged_old_new_1/missing_org_' + str(i+1) + '.csv', index=False)

In [53]:
# add info from original country code column to country column withcountry found by nominatim

for i in range(len(merged_list)):
    df = merged_list[i]
    df['country_code_original_nominatim'] = df['country_x'].str.lower()
    df['country_code_original_nominatim'] = df['country_code_original_nominatim'] .fillna(df['country_code_nominatim'])
    df['country_code_original_nominatim'] = df['country_code_original_nominatim'].replace({'uk': 'gb', 'el': 'gr'})
    #df.to_csv('data new/merged_old_new_1_country_code/country_code_' + str(i+1) + '.csv', index=False)

##### We remove duplicated columns and rename some

In [ ]:
# read organizations files with country added

org_folder = 'data new/merged_old_new_1_country_code/'

org_1 = pd.read_csv(org_folder + 'country_code_1.csv')
org_2 = pd.read_csv(org_folder + 'country_code_2.csv')
org_3 = pd.read_csv(org_folder + 'country_code_3.csv')
org_4 = pd.read_csv(org_folder + 'country_code_4.csv')
org_5 = pd.read_csv(org_folder + 'country_code_5.csv')
org_6 = pd.read_csv(org_folder + 'country_code_6.csv')
org_7 = pd.read_csv(org_folder + 'country_code_7.csv')
org_8 = pd.read_csv(org_folder + 'country_code_8.csv')
org_9 = pd.read_csv(org_folder + 'country_code_9.csv')


# we do it for each organization df 1, 2, ..., 9 -> we manually change it
# remove duplicated columns
org_9 = org_9.drop(columns=['projectID_y', 'projectAcronym_y', 'organisationID_y',
       'vatNumber_y', 'shortName_y', 'SME_y', 'activityType_y', 'street_y',
       'postCode_y', 'nutsCode_y', 'geolocation_y', 'organizationURL_y',
       'contactForm_y', 'contentUpdateDate_y', 'rcn_y', 'order_y', 'role_y',
       'ecContribution_y', 'netEcContribution_y', 'totalCost_y',
       'endOfParticipation_y', 'active_y'])

# save cleaned datasets
org_1.to_csv('data new/organizations/org_1_updated.csv', index=False)
org_2.to_csv('data new/organizations/org_2_updated.csv', index=False)
org_3.to_csv('data new/organizations/org_3_updated.csv', index=False)
org_4.to_csv('data new/organizations/org_4_updated.csv', index=False)
org_5.to_csv('data new/organizations/org_5_updated.csv', index=False)
org_6.to_csv('data new/organizations/org_6_updated.csv', index=False)
org_7.to_csv('data new/organizations/org_7_updated.csv', index=False)
org_8.to_csv('data new/organizations/org_8_updated.csv', index=False)
org_9.to_csv('data new/organizations/org_9_updated_tot.csv', index=False)

/tmp/ipykernel_2795924/873889291.py:8: DtypeWarning: Columns (3,7,12,18,44,46,47,48,49,50,52,53,54,55,56,59,63) have mixed types. Specify dtype option on import or set low_memory=False.
  org_4 = pd.read_csv(org_folder + 'country_code_4.csv')
/tmp/ipykernel_2795924/873889291.py:9: DtypeWarning: Columns (3,7,12,18,44,46,47,48,49,50,51,52,53,54,55,56,59,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  org_5 = pd.read_csv(org_folder + 'country_code_5.csv')
/tmp/ipykernel_2795924/873889291.py:10: DtypeWarning: Columns (0,3,12,44,46,47,48,49,50,51,52,53,54,55,56,59,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  org_6 = pd.read_csv(org_folder + 'country_code_6.csv')
/tmp/ipykernel_2795924/873889291.py:11: DtypeWarning: Columns (17,18,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  org_7 = pd.read_csv(org_folder + 'country_code_7.csv')
/tmp/ipykernel_2795924/873889291.py:12: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  org_8 = pd.read_csv(org_folder + 'country_code_8.csv')
/tmp/ipykernel_2795924/873889291.py:13: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  org_9 = pd.read_csv(org_folder + 'country_code_9.csv')

In [75]:
# keep only org-proj for projects until 2025

# read proj horizon europe
proj_h_eu = pd.read_csv('data new/projects/project_9.csv')

# read_organizations horizon europe
org_h_eu = pd.read_csv('data new/organizations/org_9_updated_tot.csv')

# projects in horizon europe until 2025
proj_2025 = list(proj_h_eu['id'])

# extract org-proj only for proj until 2025
org_2025 = org_h_eu[org_h_eu['projectID'].isin(proj_2025)]

# save org until 2025
org_2025.to_csv('data new/organizations/org_9_updated.csv', index=False)

/tmp/ipykernel_2795924/3723894560.py:7: DtypeWarning: Columns (6,17,18,20,21,23,24,26,38,42,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  org_h_eu = pd.read_csv('data new/organizations/org_9_updated_tot.csv')

##### NB: here we checked the column "country_code_original_nominatim" and we manually added correct country codes when mssing -> we have the total found country codes in column "country_code_ok"

### Create edgelists for countries network

In [104]:
# read organizations files with country added

org_folder = 'data new/organizations/'

org_1 = pd.read_csv(org_folder + 'org_1_updated.csv')
org_2 = pd.read_csv(org_folder + 'org_2_updated.csv')
org_3 = pd.read_csv(org_folder + 'org_3_updated.csv')
org_4 = pd.read_csv(org_folder + 'org_4_updated.csv')
org_5 = pd.read_csv(org_folder + 'org_5_updated.csv')
org_6 = pd.read_csv(org_folder + 'org_6_updated.csv')
org_7 = pd.read_csv(org_folder + 'org_7_updated.csv')
org_8 = pd.read_csv(org_folder + 'org_8_updated.csv')
org_9 = pd.read_csv(org_folder + 'org_9_updated.csv')

org_list = [org_1, org_2, org_3, org_4, org_5, org_6, org_7, org_8, org_9]

/tmp/ipykernel_2795924/570191269.py:8: DtypeWarning: Columns (3,8,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  org_4 = pd.read_csv(org_folder + 'org_4_updated.csv')
/tmp/ipykernel_2795924/570191269.py:9: DtypeWarning: Columns (3,8,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  org_5 = pd.read_csv(org_folder + 'org_5_updated.csv')
/tmp/ipykernel_2795924/570191269.py:10: DtypeWarning: Columns (3,13) have mixed types. Specify dtype option on import or set low_memory=False.
  org_6 = pd.read_csv(org_folder + 'org_6_updated.csv')
/tmp/ipykernel_2795924/570191269.py:11: DtypeWarning: Columns (18,19,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  org_7 = pd.read_csv(org_folder + 'org_7_updated.csv')
/tmp/ipykernel_2795924/570191269.py:12: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  org_8 = pd.read_csv(org_folder + 'org_8_updated.csv')
/tmp/ipykernel_2795924/570191269.py:13: DtypeWarning: Columns (18,19,21,22,24,25,27,39,43) have mixed types. Specify dtype option on import or set low_memory=False.
  org_9 = pd.read_csv(org_folder + 'org_9_updated.csv')

In [105]:
org_9

,projectID,projectAcronym,organisationID,vatNumber,name,country_code_ok,shortName,SME,activityType,street,...,county,state,state_district,country_code_nominatim,importance,granularity,city_nominatim,match_country_org_nom,index,country_code_original_nominatim
0,101234994,OPTIMALMINE,998804636,NaN,university of british columbia,ca,UBC,False,HES,AGRONOMY ROAD 102-6190,...,Metro Vancouver Regional District,British Columbia,NaN,ca,0.686967950648544,city,vancouver,yes,NaN,ca
1,101234994,OPTIMALMINE,950669162,BG822106269,asarel medet ad,bg,NaN,False,PRC,.,...,NaN,Pazardzhik,Panagiurishte,bg,0.501982567558912,city,panagyurishte,yes,NaN,bg
2,101234994,OPTIMALMINE,999881724,AU63942912684,the university of queensland,au,THE UNIVERSITY OF QUEENSLAND,False,HES,ST LUCIA,...,NaN,Queensland,NaN,au,0.669408227759282,city,brisbane city,yes,NaN,au
3,101234994,OPTIMALMINE,926249509,NaN,mining and metallurgy institute bor ltd,rs,Bor Institute,False,OTH,ZELENI BULEVAR 35,...,Jönköping County,NaN,NaN,se,0.27501,city,bor,yes,NaN,rs
4,101234994,OPTIMALMINE,999985417,GB499672470,university of newcastle upon tyne,gb,UNEW,False,HES,KINGS GATE,...,NaN,England,North of Tyne,gb,0.620469585639904,city,newcastle upon tyne,yes,NaN,gb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111675,101132079,Kaleidos,915420526,ESB67031849,wedo project intelligence made easysl,es,WeDo,True,PRC,C/ TAULAT 113 BAJOS 2 A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8041,es
111676,101132079,Kaleidos,988004074,ESG64513450,fundacio privada parc de recerca uab,es,Parc Recerca UAB,False,OTH,CAMPUS DE LA UNIVERSITAT AUTONOMA DE BCN S/N ...,...,Vallès Occidental,Catalonia,NaN,es,0.511535551158634,city,cerdanyola del vallès,yes,NaN,es
111677,101132079,Kaleidos,999993953,IT01131710376,alma mater studiorum - universita di bologna,it,UNIBO,False,HES,VIA ZAMBONI 33,...,Bologna,Emilia-Romagna,NaN,it,0.680577110926843,city,bologna,yes,NaN,it
111678,101132079,Kaleidos,999986484,ESQ0818002H,universitat autonoma de barcelona,es,UAB,False,HES,EDIF A CAMPUS DE LA UAB BELLATERRA CERDANYOLA V,...,Barcelonès,Catalonia,NaN,es,0.743564996950318,city,barcelona,yes,NaN,es
111679,101132079,Kaleidos,999874837,SE202100312001,karlstads universitet,se,KU,False,HES,UNIVERSITETSGATAN 2,...,Värmland County,NaN,NaN,se,0.590078249397657,city,karlstad,yes,NaN,se

In [87]:
# filter out only EFTA countries

efta_countries = list(pd.read_csv('participants/efta countries.csv')['country'].map(lambda x: x.lower()))

In [ ]:
# group by projectID and put all the countries into a list

output_dir = 'network efta countries/proj_countries/'

grouped_proj_country = []

count = 1
for org in org_list:

    #extract only efta countries
    org_efta = org[org['country_code_ok'].isin(efta_countries)]
    # group by projectID
    grouped_org = org_efta.groupby('projectID').agg(projectID=pd.NamedAgg(column='projectID', aggfunc='first'), country_list=pd.NamedAgg(column='country_code_ok', aggfunc=list))
    grouped_proj_country += [grouped_org]
    grouped_org.to_csv(output_dir + 'grouped_proj_country_' + str(count) + '.csv', index=False)

    count += 1

In [90]:
grouped_proj_country[7]

           projectID                                       country_list
projectID
115797        115797  [nl, dk, gb, fi, it, gb, fr, de, be, ch, at, s...
115842        115842           [nl, it, it, it, ch, gb, ch, gb, de, se]
115843        115843  [it, fi, fr, dk, be, de, dk, gb, fr, gb, fr, i...
115844        115844                                   [de, it, it, cz]
115847        115847                                       [ie, gb, be]
...              ...                                                ...
101039254  101039254                                       [gb, be, be]
101046258  101046258                                       [se, de, de]
101046657  101046657       [se, de, se, at, se, it, at, fr, at, de, de]
101048703  101048703  [se, ee, at, sk, cz, cy, fi, lu, lv, gr, no, m...
101051997  101051997  [fr, pt, cz, at, de, de, si, pl, hu, se, ie, a...

[34270 rows x 2 columns]

In [109]:
input_dir = 'network efta countries/proj_countries/'
output_dir_edge = 'network efta countries/edgelist/with self-loops/'
output_dir_edge_weighted = 'network efta countries/edgelist weighted/with self-loops/'

for i in range(9):
     print(i+1)

     df = (
          pl.read_csv(
               input_dir + 'grouped_proj_country_' + str(i+1) + '.csv',
               schema_overrides={
                    "projectID": pl.Utf8,   # keep as string
                    "country_list": pl.Utf8    # load as string first
                    }
                    )
                    .with_columns(
                         pl.col("country_list")
                         .map_elements(lambda x: ast.literal_eval(x) if x is not None else None, return_dtype=pl.List(pl.Utf8))   # safely parse only JSON-looking rows
                         .alias("country_list_list")
                         )
                         )
     print(df)

     edgelist = create_edgelist_undirected(df, 'projectID', 'country_list_list', 'alias_country_list', 'source', 'target', output_dir_edge + 'edgelist_' + str(i+1) + '.csv')
     print(edgelist)
     # normalize pairs by sorting (min, max)
     edgelist_weighted_undirected = edgelist.with_columns([
        pl.min_horizontal('source', 'target').alias('node1'),
        pl.max_horizontal('source', 'target').alias('node2'),
     ])

     # group by normalized edge and count
     edgelist_weighted_undirected_final = (
        edgelist_weighted_undirected.group_by(['node1', 'node2'])
        .len()
        .rename({"len": "weight", 'node1': 'source', 'node2': 'target'})
        .sort("weight", descending=True)
     )

     edgelist_weighted_undirected_final.write_csv(output_dir_edge_weighted + 'edgelist_weighted_' + str(i+1) + '.csv')
     
     #edgelist_weighted_undirected_final = edgelist_weighted_undirected(edgelist, 'source', 'target', 'node1', 'node2')

     #print(edgelist_weighted_undirected_final)

1
shape: (3_267, 3)
┌───────────┬────────────────────────────────┬──────────────────────┐
│ projectID ┆ country_list                   ┆ country_list_list    │
│ ---       ┆ ---                            ┆ ---                  │
│ str       ┆ str                            ┆ list[str]            │
╞═══════════╪════════════════════════════════╪══════════════════════╡
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ ["fr", "it", … "gb"] │
│ 1014-BIS  ┆ ['fr']                         ┆ ["fr"]               │
│ 1016      ┆ ['fr']                         ┆ ["fr"]               │
│ 1017      ┆ ['fr']                         ┆ ["fr"]               │
│ 1019      ┆ ['fr']                         ┆ ["fr"]               │
│ …         ┆ …                              ┆ …                    │
│ ST2*0476  ┆ ['gb', 'nl', 'be']             ┆ ["gb", "nl", "be"]   │
│ ST2*0477  ┆ ['gb', 'gr', 'gb']             ┆ ["gb", "gr", "gb"]   │
│ ST2*0478  ┆ ['ie', 'fr', 'es', 'fr']       ┆ ["ie", "fr", … "fr"] │
│ ST2*0479  ┆ ['fr', 'gb', 'it', 'it']       ┆ ["fr", "gb", … "it"] │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ ["de", "it", "it"]   │
└───────────┴────────────────────────────────┴──────────────────────┘
shape: (12_192, 4)
┌───────────┬────────────────────────────────┬────────┬────────┐
│ projectID ┆ country_list                   ┆ source ┆ target │
│ ---       ┆ ---                            ┆ ---    ┆ ---    │
│ str       ┆ str                            ┆ str    ┆ str    │
╞═══════════╪════════════════════════════════╪════════╪════════╡
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ it     ┆ fr     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ it     ┆ fr     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ it     ┆ it     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ fr     ┆ fr     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ fr     ┆ it     │
│ …         ┆ …                              ┆ …      ┆ …      │
│ ST2*0479  ┆ ['fr', 'gb', 'it', 'it']       ┆ it     ┆ gb     │
│ ST2*0479  ┆ ['fr', 'gb', 'it', 'it']       ┆ it     ┆ it     │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ it     ┆ de     │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ it     ┆ de     │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ it     ┆ it     │
└───────────┴────────────────────────────────┴────────┴────────┘
shape: (12_192, 4)
┌───────────┬────────────────────────────────┬────────┬────────┐
│ projectID ┆ country_list                   ┆ source ┆ target │
│ ---       ┆ ---                            ┆ ---    ┆ ---    │
│ str       ┆ str                            ┆ str    ┆ str    │
╞═══════════╪════════════════════════════════╪════════╪════════╡
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ it     ┆ fr     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ it     ┆ fr     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ it     ┆ it     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ fr     ┆ fr     │
│ 1007      ┆ ['fr', 'it', 'it', 'fr', 'gb'] ┆ fr     ┆ it     │
│ …         ┆ …                              ┆ …      ┆ …      │
│ ST2*0479  ┆ ['fr', 'gb', 'it', 'it']       ┆ it     ┆ gb     │
│ ST2*0479  ┆ ['fr', 'gb', 'it', 'it']       ┆ it     ┆ it     │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ it     ┆ de     │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ it     ┆ de     │
│ ST2*0480  ┆ ['de', 'it', 'it']             ┆ it     ┆ it     │
└───────────┴────────────────────────────────┴────────┴────────┘
2
shape: (3_854, 3)
┌───────────┬─────────────────────────────────┬──────────────────────┐
│ projectID ┆ country_list                    ┆ country_list_list    │
│ ---       ┆ ---                             ┆ ---                  │
│ str       ┆ str                             ┆ list[str]            │
╞═══════════╪═════════════════════════════════╪══════════════════════╡
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ ["nl", "dk", … "de"] │
│ 1650      ┆ ['de', 'fr', 'de', 'fr', 'de',… ┆ ["de", "fr", … "dk"] │
│ 1654      ┆ ['ch', 'fr', 'es', 'fr', 'fr',… ┆ ["ch", "fr", … "de"] │
│ 1655      ┆ ['be', 'be', 'fr', 'de', 'nl',… ┆ ["be", "be", … "gb"] │
│ 1656      ┆ ['it', 'gb', 'gr', 'it']        ┆ ["it", "gb", … "it"] │
│ …         ┆ …                               ┆ …                    │
│ V1066     ┆ ['fr', 'fr', 'fr', 'pt', 'de',… ┆ ["fr", "fr", … "fr"] │
│ V1067     ┆ ['it', 'de', 'se', 'fr', 'de',… ┆ ["it", "de", … "de"] │
│ V1068     ┆ ['fr', 'es', 'es', 'gb']        ┆ ["fr", "es", … "gb"] │
│ V1069     ┆ ['be', 'be', 'be', 'de', 'de',… ┆ ["be", "be", … "de"] │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ ["de", "nl", … "de"] │
└───────────┴─────────────────────────────────┴──────────────────────┘
shape: (77_199, 4)
┌───────────┬─────────────────────────────────┬────────┬────────┐
│ projectID ┆ country_list                    ┆ source ┆ target │
│ ---       ┆ ---                             ┆ ---    ┆ ---    │
│ str       ┆ str                             ┆ str    ┆ str    │
╞═══════════╪═════════════════════════════════╪════════╪════════╡
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ dk     ┆ nl     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ gb     ┆ nl     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ gb     ┆ dk     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ nl     ┆ nl     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ nl     ┆ dk     │
│ …         ┆ …                               ┆ …      ┆ …      │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ gb     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ fr     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ fr     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ es     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ gr     │
└───────────┴─────────────────────────────────┴────────┴────────┘
shape: (77_199, 4)
┌───────────┬─────────────────────────────────┬────────┬────────┐
│ projectID ┆ country_list                    ┆ source ┆ target │
│ ---       ┆ ---                             ┆ ---    ┆ ---    │
│ str       ┆ str                             ┆ str    ┆ str    │
╞═══════════╪═════════════════════════════════╪════════╪════════╡
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ dk     ┆ nl     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ gb     ┆ nl     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ gb     ┆ dk     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ nl     ┆ nl     │
│ 1648      ┆ ['nl', 'dk', 'gb', 'nl', 'de',… ┆ nl     ┆ dk     │
│ …         ┆ …                               ┆ …      ┆ …      │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ gb     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ fr     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ fr     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ es     │
│ V1073     ┆ ['de', 'nl', 'fr', 'gb', 'gr',… ┆ de     ┆ gr     │
└───────────┴─────────────────────────────────┴────────┴────────┘
3
shape: (5_514, 3)
┌───────────┬─────────────────────────────────┬──────────────────────┐
│ projectID ┆ country_list                    ┆ country_list_list    │
│ ---       ┆ ---                             ┆ ---                  │
│ str       ┆ str                             ┆ list[str]            │
╞═══════════╪═════════════════════════════════╪══════════════════════╡
│ 10001     ┆ ['es']                          ┆ ["es"]               │
│ 10024     ┆ ['at']                          ┆ ["at"]               │
│ 10043     ┆ ['ie', 'de']                    ┆ ["ie", "de"]         │
│ 10056     ┆ ['fr', 'fr', 'fr']              ┆ ["fr", "fr", "fr"]   │
│ 10070     ┆ ['it']                          ┆ ["it"]               │
│ …         ┆ …                               ┆ …                    │
│ V2063     ┆ ['gr', 'it', 'it', 'fi', 'dk',… ┆ ["gr", "it", … "de"] │
│ V2064     ┆ ['gb', 'fr', 'fr', 'be', 'it',… ┆ ["gb", "fr", … "fr"] │
│ V2065     ┆ ['gb', 'gb', 'gb', 'gb', 'nl',… ┆ ["gb", "gb", … "de"] │
│ V2066     ┆ ['es', 'es', 'es', 'es']        ┆ ["es", "es", … "es"] │
│ V2067     ┆ ['dk']                          ┆ ["dk"]               │
└───────────┴─────────────────────────────────┴──────────────────────┘
shape: (131_741, 4)
┌───────────┬──────────────────────────┬────────┬────────┐
│ projectID ┆ country_list             ┆ source ┆ target │
│ ---       ┆ ---                      ┆ ---    ┆ ---    │
│ str       ┆ str                      ┆ str    ┆ str    │
╞═══════════╪══════════════════════════╪════════╪════════╡
│ 10043     ┆ ['ie', 'de']             ┆ de     ┆ ie     │
│ 10056     ┆ ['fr', 'fr', 'fr']       ┆ fr     ┆ fr     │
│ 10056     ┆ ['fr', 'fr', 'fr']       ┆ fr     ┆ fr     │
│ 10056     ┆ ['fr', 'fr', 'fr']       ┆ fr     ┆ fr     │
│ 1008      ┆ ['nl', 'gb', 'gb', 'gb'] ┆ gb     ┆ nl     │
│ …         ┆ …                        ┆ …      ┆ …      │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
└───────────┴──────────────────────────┴────────┴────────┘
shape: (131_741, 4)
┌───────────┬──────────────────────────┬────────┬────────┐
│ projectID ┆ country_list             ┆ source ┆ target │
│ ---       ┆ ---                      ┆ ---    ┆ ---    │
│ str       ┆ str                      ┆ str    ┆ str    │
╞═══════════╪══════════════════════════╪════════╪════════╡
│ 10043     ┆ ['ie', 'de']             ┆ de     ┆ ie     │
│ 10056     ┆ ['fr', 'fr', 'fr']       ┆ fr     ┆ fr     │
│ 10056     ┆ ['fr', 'fr', 'fr']       ┆ fr     ┆ fr     │
│ 10056     ┆ ['fr', 'fr', 'fr']       ┆ fr     ┆ fr     │
│ 1008      ┆ ['nl', 'gb', 'gb', 'gb'] ┆ gb     ┆ nl     │
│ …         ┆ …                        ┆ …      ┆ …      │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
│ V2066     ┆ ['es', 'es', 'es', 'es'] ┆ es     ┆ es     │
└───────────┴──────────────────────────┴────────┴────────┘
4
shape: (14_484, 3)
┌──────────────┬─────────────────────────────────┬──────────────────────┐
│ projectID    ┆ country_list                    ┆ country_list_list    │
│ ---          ┆ ---                             ┆ ---                  │
│ str          ┆ str                             ┆ list[str]            │
╞══════════════╪═════════════════════════════════╪══════════════════════╡
│ 1000         ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ ["fr", "fr", … "be"] │
│ 1009         ┆ ['fr', 'de', 'it', 'de']        ┆ ["fr", "de", … "de"] │
│ 1010         ┆ ['gb', 'it', 'es', 'lu', 'es']  ┆ ["gb", "it", … "es"] │
│ 1022         ┆ ['se', 'gb', 'de', 'de']        ┆ ["se", "gb", … "de"] │
│ 1030         ┆ ['de', 'es']                    ┆ ["de", "es"]         │
│ …            ┆ …                               ┆ …                    │
│ WE.-00250-97 ┆ ['fr']                          ┆ ["fr"]               │
│ WE.-00254-97 ┆ ['fr']                          ┆ ["fr"]               │
│ WE.-00296-98 ┆ ['dk']                          ┆ ["dk"]               │
│ WE.-00305-98 ┆ ['es']                          ┆ ["es"]               │
│ WE.-00355-95 ┆ ['it']                          ┆ ["it"]               │
└──────────────┴─────────────────────────────────┴──────────────────────┘
shape: (248_108, 4)
┌───────────────┬─────────────────────────────────┬────────┬────────┐
│ projectID     ┆ country_list                    ┆ source ┆ target │
│ ---           ┆ ---                             ┆ ---    ┆ ---    │
│ str           ┆ str                             ┆ str    ┆ str    │
╞═══════════════╪═════════════════════════════════╪════════╪════════╡
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ fr     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ fr     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ fr     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ dk     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ dk     ┆ fr     │
│ …             ┆ …                               ┆ …      ┆ …      │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ nl     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ es     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ dk     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ de     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ fr     │
└───────────────┴─────────────────────────────────┴────────┴────────┘
shape: (248_108, 4)
┌───────────────┬─────────────────────────────────┬────────┬────────┐
│ projectID     ┆ country_list                    ┆ source ┆ target │
│ ---           ┆ ---                             ┆ ---    ┆ ---    │
│ str           ┆ str                             ┆ str    ┆ str    │
╞═══════════════╪═════════════════════════════════╪════════╪════════╡
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ fr     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ fr     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ fr     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ dk     ┆ fr     │
│ 1000          ┆ ['fr', 'fr', 'fr', 'dk', 'dk',… ┆ dk     ┆ fr     │
│ …             ┆ …                               ┆ …      ┆ …      │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ nl     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ es     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ dk     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ de     │
│ WA-98-RS.3011 ┆ ['be', 'nl', 'it', 'nl', 'es',… ┆ gb     ┆ fr     │
└───────────────┴─────────────────────────────────┴────────┴────────┘
5
shape: (16_730, 3)
┌────────────────────┬─────────────────────────────────┬──────────────────────┐
│ projectID          ┆ country_list                    ┆ country_list_list    │
│ ---                ┆ ---                             ┆ ---                  │
│ str                ┆ str                             ┆ list[str]            │
╞════════════════════╪═════════════════════════════════╪══════════════════════╡
│ 1                  ┆ ['it']                          ┆ ["it"]               │
│ 109                ┆ ['nl']                          ┆ ["nl"]               │
│ 10968              ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ ["gb", "gb", … "fr"] │
│ 10971              ┆ ['it', 'be', 'be', 'nl']        ┆ ["it", "be", … "nl"] │
│ 10980              ┆ ['gb', 'de', 'fr', 'fr', 'ch',… ┆ ["gb", "de", … "fi"] │
│ …                  ┆ …                               ┆ …                    │
│ QLRI-CT-2002-81333 ┆ ['es', 'fr', 'ch', 'de', 'gb',… ┆ ["es", "fr", … "it"] │
│ QLRI-CT-2002-81457 ┆ ['fr', 'fr', 'fr']              ┆ ["fr", "fr", "fr"]   │
│ QLRI-CT-2002-90383 ┆ ['pl']                          ┆ ["pl"]               │
│ QLRS-2002-00799    ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ ["it", "no", … "gb"] │
│ QOL-CT-1999-1111   ┆ ['es']                          ┆ ["es"]               │
└────────────────────┴─────────────────────────────────┴──────────────────────┘
shape: (423_739, 4)
┌─────────────────┬─────────────────────────────────┬────────┬────────┐
│ projectID       ┆ country_list                    ┆ source ┆ target │
│ ---             ┆ ---                             ┆ ---    ┆ ---    │
│ str             ┆ str                             ┆ str    ┆ str    │
╞═════════════════╪═════════════════════════════════╪════════╪════════╡
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ gb     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ gb     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ gb     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ de     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ de     ┆ gb     │
│ …               ┆ …                               ┆ …      ┆ …      │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ fr     ┆ dk     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ it     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ no     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ dk     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ fr     │
└─────────────────┴─────────────────────────────────┴────────┴────────┘
shape: (423_739, 4)
┌─────────────────┬─────────────────────────────────┬────────┬────────┐
│ projectID       ┆ country_list                    ┆ source ┆ target │
│ ---             ┆ ---                             ┆ ---    ┆ ---    │
│ str             ┆ str                             ┆ str    ┆ str    │
╞═════════════════╪═════════════════════════════════╪════════╪════════╡
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ gb     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ gb     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ gb     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ de     ┆ gb     │
│ 10968           ┆ ['gb', 'gb', 'gb', 'de', 'gb',… ┆ de     ┆ gb     │
│ …               ┆ …                               ┆ …      ┆ …      │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ fr     ┆ dk     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ it     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ no     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ dk     │
│ QLRS-2002-00799 ┆ ['it', 'no', 'dk', 'fr', 'gb']  ┆ gb     ┆ fr     │
└─────────────────┴─────────────────────────────────┴────────┴────────┘
6
shape: (9_884, 3)
┌───────────┬─────────────────────────────────┬──────────────────────┐
│ projectID ┆ country_list                    ┆ country_list_list    │
│ ---       ┆ ---                             ┆ ---                  │
│ str       ┆ str                             ┆ list[str]            │
╞═══════════╪═════════════════════════════════╪══════════════════════╡
│ 0         ┆ ['ee', 'ee']                    ┆ ["ee", "ee"]         │
│ 10003     ┆ ['it']                          ┆ ["it"]               │
│ 10004     ┆ ['gb']                          ┆ ["gb"]               │
│ 10022     ┆ ['ie']                          ┆ ["ie"]               │
│ 10036     ┆ ['gb', 'se', 'de', 'nl', 'gb',… ┆ ["gb", "se", … "dk"] │
│ …         ┆ …                               ┆ …                    │
│ JRC-2113  ┆ ['it']                          ┆ ["it"]               │
│ JRC-2212  ┆ ['it']                          ┆ ["it"]               │
│ JRC-2221  ┆ ['it']                          ┆ ["it"]               │
│ JRC-2222  ┆ ['it']                          ┆ ["it"]               │
│ JRC-3142  ┆ ['be']                          ┆ ["be"]               │
└───────────┴─────────────────────────────────┴──────────────────────┘
shape: (605_556, 4)
┌───────────┬─────────────────────────────────┬────────┬────────┐
│ projectID ┆ country_list                    ┆ source ┆ target │
│ ---       ┆ ---                             ┆ ---    ┆ ---    │
│ str       ┆ str                             ┆ str    ┆ str    │
╞═══════════╪═════════════════════════════════╪════════╪════════╡
│ 0         ┆ ['ee', 'ee']                    ┆ ee     ┆ ee     │
│ 10036     ┆ ['gb', 'se', 'de', 'nl', 'gb',… ┆ se     ┆ gb     │
│ 10036     ┆ ['gb', 'se', 'de', 'nl', 'gb',… ┆ de     ┆ gb     │
│ 10036     ┆ ['gb', 'se', 'de', 'nl', 'gb',… ┆ de     ┆ se     │
│ 10036     ┆ ['gb', 'se', 'de', 'nl', 'gb',… ┆ nl     ┆ gb     │
│ …         ┆ …                               ┆ …      ┆ …      │
│ 9876      ┆ ['mt', 'gb', 'se', 'fr']        ┆ se     ┆ mt     │
│ 9876      ┆ ['mt', 'gb', 'se', 'fr']        ┆ se     ┆ gb     │
│ 9876      ┆ ['mt', 'gb', 'se', 'fr']        ┆ fr     ┆ mt     │

### Create countries network in nx

In [111]:
# convert df edgelist into list edgelist

list_edgelist_list = []

for i in range(9):
    df_edgelist = pd.read_csv('network efta countries/edgelist weighted/with self-loops/edgelist_weighted_' + str(i+1) + '.csv')
    list_edgelist = df_edgelist_to_list_edgelist(df_edgelist, 'source', 'target', ['weight'])
    print(list_edgelist)
    list_edgelist_list += [list_edgelist]

[('fr', 'gb', {'weight': 944}), ('de', 'fr', {'weight': 806}), ('fr', 'fr', {'weight': 732}), ('de', 'gb', {'weight': 727}), ('fr', 'it', {'weight': 692}), ('de', 'it', {'weight': 443}), ('gb', 'gb', {'weight': 443}), ('de', 'de', {'weight': 417}), ('gb', 'it', {'weight': 416}), ('gb', 'nl', {'weight': 374}), ('be', 'fr', {'weight': 374}), ('it', 'it', {'weight': 302}), ('fr', 'nl', {'weight': 289}), ('de', 'nl', {'weight': 268}), ('be', 'de', {'weight': 259}), ('be', 'gb', {'weight': 230}), ('dk', 'gb', {'weight': 212}), ('es', 'fr', {'weight': 195}), ('it', 'nl', {'weight': 176}), ('de', 'dk', {'weight': 165}), ('gb', 'ie', {'weight': 156}), ('be', 'it', {'weight': 138}), ('be', 'nl', {'weight': 133}), ('es', 'gb', {'weight': 132}), ('de', 'es', {'weight': 125}), ('fr', 'ie', {'weight': 121}), ('fr', 'gr', {'weight': 121}), ('dk', 'fr', {'weight': 120}), ('be', 'be', {'weight': 117}), ('gb', 'gr', {'weight': 110}), ('de', 'gr', {'weight': 108}), ('nl', 'nl', {'weight': 108}), ('gb', 'pt', {'weight': 107}), ('de', 'ie', {'weight': 103}), ('es', 'it', {'weight': 99}), ('dk', 'nl', {'weight': 97}), ('fr', 'pt', {'weight': 90}), ('dk', 'it', {'weight': 84}), ('de', 'pt', {'weight': 80}), ('gr', 'it', {'weight': 74}), ('be', 'dk', {'weight': 73}), ('es', 'es', {'weight': 70}), ('es', 'pt', {'weight': 70}), ('ie', 'it', {'weight': 68}), ('ie', 'nl', {'weight': 63}), ('dk', 'dk', {'weight': 62}), ('be', 'ie', {'weight': 60}), ('es', 'nl', {'weight': 60}), ('gr', 'nl', {'weight': 58}), ('be', 'es', {'weight': 50}), ('it', 'pt', {'weight': 47}), ('dk', 'es', {'weight': 45}), ('dk', 'ie', {'weight': 44}), ('nl', 'pt', {'weight': 40}), ('es', 'ie', {'weight': 39}), ('be', 'pt', {'weight': 39}), ('dk', 'gr', {'weight': 39}), ('pt', 'pt', {'weight': 38}), ('be', 'gr', {'weight': 36}), ('es', 'gr', {'weight': 35}), ('ie', 'ie', {'weight': 30}), ('ie', 'pt', {'weight': 27}), ('gr', 'gr', {'weight': 27}), ('dk', 'pt', {'weight': 26}), ('gr', 'pt', {'weight': 24}), ('gr', 'ie', {'weight': 22}), ('fr', 'se', {'weight': 18}), ('gb', 'se', {'weight': 17}), ('dk', 'se', {'weight': 17}), ('ch', 'fr', {'weight': 16}), ('nl', 'se', {'weight': 16}), ('de', 'se', {'weight': 13}), ('fi', 'gb', {'weight': 13}), ('it', 'se', {'weight': 12}), ('gr', 'se', {'weight': 12}), ('es', 'se', {'weight': 11}), ('be', 'se', {'weight': 11}), ('pt', 'se', {'weight': 10}), ('ch', 'gb', {'weight': 10}), ('ie', 'se', {'weight': 10}), ('gb', 'lu', {'weight': 9}), ('fi', 'fr', {'weight': 8}), ('ch', 'nl', {'weight': 8}), ('gb', 'no', {'weight': 7}), ('fr', 'no', {'weight': 7}), ('fi', 'se', {'weight': 6}), ('be', 'lu', {'weight': 5}), ('dk', 'fi', {'weight': 5}), ('fi', 'fi', {'weight': 5}), ('de', 'fi', {'weight': 4}), ('fi', 'nl', {'weight': 4}), ('at', 'de', {'weight': 4}), ('de', 'lu', {'weight': 3}), ('fr', 'lu', {'weight': 3}), ('ch', 'it', {'weight': 3}), ('at', 'fr', {'weight': 3}), ('ch', 'es', {'weight': 3}), ('at', 'nl', {'weight': 3}), ('it', 'no', {'weight': 3}), ('de', 'no', {'weight': 2}), ('be', 'ch', {'weight': 2}), ('no', 'pt', {'weight': 2}), ('fi', 'gr', {'weight': 2}), ('nl', 'no', {'weight': 2}), ('dk', 'no', {'weight': 2}), ('es', 'no', {'weight': 2}), ('fi', 'no', {'weight': 2}), ('ch', 'ie', {'weight': 1}), ('at', 'gr', {'weight': 1}), ('ch', 'dk', {'weight': 1}), ('at', 'it', {'weight': 1}), ('fi', 'it', {'weight': 1}), ('ch', 'gr', {'weight': 1}), ('es', 'fi', {'weight': 1}), ('at', 'be', {'weight': 1}), ('ch', 'de', {'weight': 1}), ('at', 'dk', {'weight': 1}), ('gr', 'no', {'weight': 1}), ('at', 'ch', {'weight': 1}), ('at', 'ie', {'weight': 1}), ('se', 'se', {'weight': 1}), ('no', 'no', {'weight': 1}), ('be', 'no', {'weight': 1}), ('lu', 'lu', {'weight': 1}), ('no', 'se', {'weight': 1})]
[('de', 'fr', {'weight': 4587}), ('de', 'gb', {'weight': 4052}), ('fr', 'gb', {'weight': 3971}), ('fr', 'it', {'weight': 2807}), ('de', 'de', {'weight': 2732}), ('fr', 'fr', {'weight': 2702}), ('de', 'it', {'weight': 2527}), ('de', 'nl', {'weight': 2278}), ('gb', 'it', {'weight': 2101}), ('gb', 'nl', {'weight': 1998}), ('es', 'fr', {'weight': 1993}), ('gb', 'gb', {'weight': 1935}), ('fr', 'nl', {'weight': 1869}), ('be', 'fr', {'weight': 1693}), ('de', 'es', {'weight': 1643}), ('be', 'de', {'weight': 1579}), ('es', 'gb', {'weight': 1470}), ('es', 'it', {'weight': 1261}), ('be', 'gb', {'weight': 1251}), ('it', 'it', {'weight': 1209}), ('de', 'dk', {'weight': 1137}), ('it', 'nl', {'weight': 1074}), ('dk', 'gb', {'weight': 970}), ('dk', 'fr', {'weight': 865}), ('fr', 'gr', {'weight': 855}), ('be', 'nl', {'weight': 838}), ('gb', 'gr', {'weight': 826}), ('be', 'it', {'weight': 806}), ('es', 'nl', {'weight': 795}), ('de', 'gr', {'weight': 776}), ('fr', 'pt', {'weight': 771}), ('nl', 'nl', {'weight': 711}), ('gb', 'ie', {'weight': 665}), ('dk', 'nl', {'weight': 640}), ('gb', 'pt', {'weight': 634}), ('de', 'pt', {'weight': 624}), ('be', 'es', {'weight': 600}), ('gr', 'it', {'weight': 590}), ('es', 'es', {'weight': 587}), ('de', 'ie', {'weight': 567}), ('gb', 'se', {'weight': 556}), ('fr', 'ie', {'weight': 545}), ('dk', 'it', {'weight': 531}), ('de', 'se', {'weight': 529}), ('it', 'pt', {'weight': 483}), ('es', 'pt', {'weight': 464}), ('be', 'dk', {'weight': 462}), ('fr', 'se', {'weight': 443}), ('dk', 'es', {'weight': 428}), ('be', 'be', {'weight': 407}), ('es', 'gr', {'weight': 394}), ('ie', 'it', {'weight': 367}), ('ch', 'de', {'weight': 352}), ('ie', 'nl', {'weight': 340}), ('gr', 'nl', {'weight': 337}), ('nl', 'pt', {'weight': 335}), ('ch', 'fr', {'weight': 314}), ('be', 'gr', {'weight': 310}), ('nl', 'se', {'weight': 283}), ('es', 'ie', {'weight': 265}), ('it', 'se', {'weight': 254}), ('be', 'pt', {'weight': 253}), ('de', 'fi', {'weight': 245}), ('dk', 'dk', {'weight': 242}), ('fi', 'gb', {'weight': 230}), ('ch', 'gb', {'weight': 230}), ('be', 'ie', {'weight': 229}), ('dk', 'gr', {'weight': 221}), ('gr', 'gr', {'weight': 213}), ('de', 'no', {'weight': 213}), ('gr', 'pt', {'weight': 208}), ('dk', 'pt', {'weight': 201}), ('ch', 'it', {'weight': 197}), ('es', 'se', {'weight': 191}), ('fi', 'fr', {'weight': 190}), ('pt', 'pt', {'weight': 189}), ('ch', 'nl', {'weight': 189}), ('dk', 'ie', {'weight': 183}), ('be', 'se', {'weight': 177}), ('gb', 'no', {'weight': 166}), ('dk', 'se', {'weight': 158}), ('fi', 'it', {'weight': 155}), ('fr', 'no', {'weight': 148}), ('fi', 'nl', {'weight': 141}), ('gr', 'ie', {'weight': 140}), ('ch', 'es', {'weight': 140}), ('ie', 'pt', {'weight': 134}), ('es', 'fi', {'weight': 123}), ('be', 'ch', {'weight': 122}), ('pt', 'se', {'weight': 104}), ('ie', 'ie', {'weight': 102}), ('be', 'fi', {'weight': 98}), ('nl', 'no', {'weight': 96}), ('dk', 'fi', {'weight': 92}), ('it', 'no', {'weight': 91}), ('gr', 'se', {'weight': 90}), ('at', 'de', {'weight': 89}), ('ch', 'dk', {'weight': 87}), ('ie', 'se', {'weight': 86}), ('at', 'fr', {'weight': 84}), ('se', 'se', {'weight': 82}), ('at', 'gb', {'weight': 74}), ('ch', 'se', {'weight': 68}), ('ch', 'pt', {'weight': 64}), ('es', 'no', {'weight': 62}), ('ch', 'gr', {'weight': 62}), ('fi', 'se', {'weight': 60}), ('fi', 'pt', {'weight': 59}), ('ch', 'ie', {'weight': 57}), ('be', 'no', {'weight': 55}), ('fi', 'gr', {'weight': 53}), ('no', 'se', {'weight': 53}), ('at', 'it', {'weight': 49}), ('dk', 'no', {'weight': 48}), ('fi', 'ie', {'weight': 45}), ('de', 'lu', {'weight': 41}), ('fr', 'lu', {'weight': 41}), ('ch', 'fi', {'weight': 39}), ('ch', 'ch', {'weight': 37}), ('gr', 'no', {'weight': 34}), ('be', 'lu', {'weight': 33}), ('at', 'nl', {'weight': 29}), ('at', 'es', {'weight': 26}), ('fi', 'no', {'weight': 25}), ('it', 'lu', {'weight': 25}), ('no', 'no', {'weight': 25}), ('gb', 'lu', {'weight': 21}), ('at', 'be', {'weight': 21}), ('ch', 'no', {'weight': 20}), ('fi', 'fi', {'weight': 19}), ('lu', 'nl', {'weight': 19}), ('no', 'pt', {'weight': 17}), ('es', 'lu', {'weight': 17}), ('at', 'gr', {'weight': 16}), ('dk', 'lu', {'weight': 13}), ('at', 'ie', {'weight': 12}), ('ie', 'no', {'weight': 12}), ('ie', 'lu', {'weight': 11}), ('at', 'se', {'weight': 11}), ('at', 'pt', {'weight': 11}), ('lu', 'pt', {'weight': 11}), ('at', 'dk', {'weight': 10}), ('gr', 'lu', {'weight': 10}), ('ch', 'lu', {'weight': 9}), ('lu', 'se', {'weight': 8}), ('at', 'at', {'weight': 8}), ('at', 'no', {'weight': 6}), ('fr', 'is', {'weight': 4}), ('de', 'li', {'weight': 4}), ('at', 'ch', {'weight': 4}), ('is', 'it', {'weight': 3}), ('fi', 'lu', {'weight': 3}), ('is', 'se', {'weight': 2}), ('at', 'fi', {'weight': 2}), ('de', 'is', {'weight': 2}), ('gr', 'is', {'weight': 2}), ('fr', 'li', {'weight': 2}), ('gb', 'is', {'weight': 2}), ('it', 'li', {'weight': 1}), ('li', 'nl', {'weight': 1}), ('es', 'li', {'weight': 1}), ('is', 'pt', {'weight': 1}), ('be', 'is', {'weight': 1}), ('is', 'is', {'weight': 1})]
[('de', 'fr', {'weight': 7255}), ('de', 'gb', {'weight': 7039}), ('fr', 'gb', {'weight': 6730}), ('fr', 'it', {'weight': 4787}), ('fr', 'fr', {'weight': 4732}), ('de', 'de', {'weight': 4564}), ('de', 'it', {'weight': 4079}), ('gb', 'it', {'weight': 3915}), ('gb', 'gb', {'weight': 3798}), ('es', 'fr', {'weight': 3199}), ('gb', 'nl', {'weight': 3180}), ('de', 'nl', {'weight': 3141}), ('fr', 'nl', {'weight': 2678}), ('es', 'gb', {'weight': 2670}), ('de', 'es', {'weight': 2643}), ('it', 'it', {'weight': 2351}), ('be', 'fr', {'weight': 2169}), ('es', 'it', {'weight': 2153}), ('be', 'de', {'weight': 1977}), ('be', 'gb', {'weight': 1735}), ('gb', 'gr', {'weight': 1730}), ('de', 'gr', {'weight': 1723}), ('fr', 'gr', {'weight': 1601}), ('dk', 'gb', {'weight': 1518}), ('it', 'nl', {'weight': 1425}), ('de', 'dk', {'weight': 1404}), ('gr', 'it', {'weight': 1283}), ('fr', 'pt', {'weight': 1257}), ('gb', 'pt', {'weight': 1240}), ('es', 'es', {'weight': 1224}), ('dk', 'fr', {'weight': 1158}), ('de', 'se', {'weight': 1150}), ('es', 'nl', {'weight': 1141}), ('be', 'it', {'weight': 1083}), ('gb', 'ie', {'weight': 1082}), ('de', 'pt', {'weight': 1075}), ('gb', 'se', {'weight': 1071}), ('fr', 'se', {'weight': 1016}), ('nl', 'nl', {'weight': 958}), ('be', 'nl', {'weight': 957}), ('gr', 'gr', {'weight': 879}), ('de', 'ie', {'weight': 871}), ('fr', 'ie', {'weight': 849}), ('es', 'gr', {'weight': 843}), ('it', 'pt', {'weight': 831}), ('be', 'es', {'weight': 793}), ('es', 'pt', {'weight': 791}), ('dk', 'nl', {'weight': 758}), ('ch', 'de', {'weight': 744}), ('ch', 'fr', {'weight': 727}), ('gr', 'nl', {'weight': 694}), ('be', 'be', {'weight': 677}), ('dk', 'it', {'weight': 669}), ('ch', 'gb', {'weight': 597}), ('gb', 'no', {'weight': 583}), ('ie', 'it', {'weight': 548}), ('nl', 'se', {'weight': 548}), ('de', 'fi', {'weight': 546}), ('it', 'se', {'weight': 536}), ('nl', 'pt', {'weight': 521}), ('dk', 'es', {'weight': 510}), ('be', 'gr', {'weight': 487}), ('de', 'no', {'weight': 480}), ('ie', 'nl', {'weight': 477}), ('fi', 'gb', {'weight': 464}), ('fr', 'no', {'weight': 464}), ('ch', 'it', {'weight': 455}), ('gr', 'pt', {'weight': 445}), ('es', 'ie', {'weight': 440}), ('at', 'de', {'weight': 426}), ('fi', 'fr', {'weight': 409}), ('be', 'pt', {'weight': 390}), ('be', 'dk', {'weight': 383}), ('dk', 'gr', {'weight': 379}), ('dk', 'dk', {'weight': 357}), ('es', 'se', {'weight': 345}), ('be', 'se', {'weight': 344}), ('pt', 'pt', {'weight': 344}), ('dk', 'se', {'weight': 340}), ('ch', 'nl', {'weight': 321}), ('at', 'fr', {'weight': 310}), ('be', 'ie', {'weight': 294}), ('at', 'gb', {'weight': 279}), ('dk', 'pt', {'weight': 272}), ('nl', 'no', {'weight': 269}), ('gr', 'ie', {'weight': 265}), ('dk', 'ie', {'weight': 265}), ('ch', 'es', {'weight': 263}), ('fi', 'nl', {'weight': 261}), ('fi', 'it', {'weight': 254}), ('at', 'it', {'weight': 244}), ('it', 'no', {'weight': 236}), ('ie', 'pt', {'weight': 234}), ('dk', 'no', {'weight': 232}), ('gr', 'se', {'weight': 215}), ('be', 'ch', {'weight': 213}), ('se', 'se', {'weight': 209}), ('es', 'no', {'weight': 196}), ('es', 'fi', {'weight': 195}), ('ie', 'ie', {'weight': 188}), ('dk', 'fi', {'weight': 170}), ('ie', 'se', {'weight': 167}), ('pt', 'se', {'weight': 154}), ('at', 'nl', {'weight': 146}), ('ch', 'gr', {'weight': 143}), ('fi', 'gr', {'weight': 141}), ('no', 'se', {'weight': 139}), ('be', 'no', {'weight': 132}), ('ch', 'dk', {'weight': 131}), ('fi', 'se', {'weight': 126}), ('ch', 'se', {'weight': 122}), ('be', 'fi', {'weight': 122}), ('no', 'pt', {'weight': 117}), ('at', 'es', {'weight': 116}), ('fi', 'fi', {'weight': 112}), ('gr', 'no', {'weight': 110}), ('fi', 'ie', {'weight': 107}), ('ch', 'pt', {'weight': 100}), ('no', 'no', {'weight': 92}), ('at', 'gr', {'weight': 91}), ('ch', 'ie', {'weight': 90}), ('ie', 'no', {'weight': 89}), ('ch', 'fi', {'weight': 87}), ('at', 'se', {'weight': 84}), ('fi', 'pt', {'weight': 83}), ('at', 'be', {'weight': 81}), ('fi', 'no', {'weight': 72}), ('ch', 'no', {'weight': 70}), ('at', 'dk', {'weight': 69}), ('ch', 'ch', {'weight': 61}), ('at', 'ch', {'weight': 50}), ('at', 'pt', {'weight': 49}), ('at', 'fi', {'weight': 45}), ('at', 'ie', {'weight': 44}), ('de', 'lu', {'weight': 43}), ('at', 'no', {'weight': 42}), ('gb', 'is', {'weight': 37}), ('fr', 'lu', {'weight': 36}), ('de', 'is', {'weight': 35}), ('gb', 'pl', {'weight': 32}), ('at', 'at', {'weight': 32}), ('de', 'pl', {'weight': 30}), ('dk', 'is', {'weight': 30}), ('de', 'hu', {'weight': 28}), ('be', 'lu', {'weight': 27}), ('gb', 'hu', {'weight': 27}), ('gb', 'lu', {'weight': 26}), ('fr', 'is', {'weight': 24}), ('gr', 'hu', {'weight': 20}), ('es', 'is', {'weight': 20}), ('es', 'pl', {'weight': 19}), ('gr', 'pl', {'weight': 19}), ('is', 'no', {'weight': 19}), ('is', 'nl', {'weight': 18}), ('hu', 'it', {'weight': 17}), ('gb', 'ro', {'weight': 17}), ('it', 'pl', {'weight': 16}), ('is', 'it', {'weight': 16}), ('fr', 'pl', {'weight': 16}), ('is', 'se', {'weight': 15}), ('gr', 'lu', {'weight': 15}), ('es', 'hu', {'weight': 15}), ('pl', 'pt', {'weight': 15}), ('it', 'lu', {'weight': 14}), ('hu', 'pt', {'weight': 14}), ('lu', 'nl', {'weight': 14}), ('fr', 'hu', {'weight': 14}), ('es', 'lu', {'weight': 14}), ('ie', 'is', {'weight': 13}), ('nl', 'pl', {'weight': 13}), ('is', 'pt', {'weight': 11}), ('ie', 'lu', {'weight': 10}), ('gr', 'is', {'weight': 10}), ('ch', 'lu', {'weight': 10}), ('de', 'ro', {'weight': 9}), ('hu', 'pl', {'weight': 9}), ('pl', 'se', {'weight': 9}), ('dk', 'lu', {'weight': 9}), ('de', 'sk', {'weight': 8}), ('hu', 'nl', {'weight': 8}), ('gr', 'ro', {'weight': 8}), ('gb', 'sk', {'weight': 8}), ('be', 'is', {'weight': 7}), ('no', 'pl', {'weight': 7}), ('fr', 'ro', {'weight': 7}), ('is', 'is', {'weight': 7}), ('fi', 'is', {'weight': 7}), ('gr', 'sk', {'weight': 6}), ('be', 'pl', {'weight': 6}), ('it', 'si', {'weight': 6}), ('hu', 'se', {'weight': 6}), ('at', 'lu', {'weight': 6}), ('es', 'ro', {'weight': 6}), ('nl', 'ro', {'weight': 5}), ('it', 'ro', {'weight': 5}), ('dk', 'hu', {'weight': 5}), ('es', 'sk', {'weight': 5}), ('lu', 'se', {'weight': 5}), ('lu', 'pt', {'weight': 5}), ('ie', 'pl', {'weight': 4}), ('fr', 'si', {'weight': 4}), ('pt', 'ro', {'weight': 4}), ('de', 'si', {'weight': 4}), ('it', 'sk', {'weight': 4}), ('lu', 'no', {'weight': 4}), ('gb', 'si', {'weight': 4}), ('be', 'hu', {'weight': 4}), ('pt', 'sk', {'weight': 4}), ('cy', 'fr', {'weight': 4}), ('fr', 'sk', {'weight': 4}), ('be', 'ro', {'weight': 4}), ('fi', 'hu', {'weight': 4}), ('dk', 'pl', {'weight': 4}), ('fi', 'ro', {'weight': 3}), ('dk', 'ro', {'weight': 3}), ('ch', 'is', {'weight': 3}), ('hu', 'sk', {'weight': 3}), ('cz', 'no', {'weight': 3}), ('cz', 'es', {'weight': 3}), ('hu', 'hu', {'weight': 3}), ('cy', 'gr', {'weight': 3}), ('ro', 'se', {'weight': 3}), ('pl', 'ro', {'weight': 3}), ('pl', 'pl', {'weight': 3}), ('fi', 'pl', {'weight': 3}), ('pl', 'sk', {'weight': 3}), ('hu', 'ie', {'weight': 3}), ('at', 'pl', {'weight': 3}), ('hu', 'no', {'weight': 3}), ('hu', 'ro', {'weight': 3}), ('se', 'sk', {'weight': 2}), ('be', 'si', {'weight': 2}), ('cz', 'gb', {'weight': 2}), ('at', 'cz', {'weight': 2}), ('cy', 'gb', {'weight': 2}), ('at', 'is', {'weight': 2}), ('cz', 'it', {'weight': 2}), ('fi', 'lu', {'weight': 2}), ('bg', 'fr', {'weight': 2}), ('ie', 'ro', {'weight': 2}), ('nl', 'si', {'weight': 2}), ('nl', 'sk', {'weight': 2}), ('ch', 'pl', {'weight': 2}), ('pt', 'si', {'weight': 2}), ('ie', 'sk', {'weight': 1}), ('fi', 'sk', {'weight': 1}), ('gr', 'si', {'weight': 1}), ('is', 'lu', {'weight': 1}), ('be', 'cy', {'weight': 1}), ('cy', 'pt', {'weight': 1}), ('ee', 'pl', {'weight': 1}), ('cz', 'fr', {'weight': 1}), ('bg', 'es', {'weight': 1}), ('at', 'hu', {'weight': 1}), ('cz', 'de', {'weight': 1}), ('lu', 'lu', {'weight': 1}), ('ee', 'se', {'weight': 1}), ('cz', 'dk', {'weight': 1}), ('ie', 'si', {'weight': 1}), ('cz', 'hu', {'weight': 1}), ('es', 'si', {'weight': 1}), ('dk', 'sk', {'weight': 1}), ('no', 'ro', {'weight': 1}), ('ee', 'nl', {'weight': 1}), ('cy', 'nl', {'weight': 1}), ('cz', 'pl', {'weight': 1}), ('at', 'si', {'weight': 1}), ('de', 'ee', {'weight': 1}), ('cz', 'pt', {'weight': 1}), ('ro', 'sk', {'weight': 1}), ('at', 'cy', {'weight': 1}), ('cz', 'nl', {'weight': 1}), ('cy', 'es', {'weight': 1}), ('be', 'sk', {'weight': 1}), ('se', 'si', {'weight': 1}), ('no', 'sk', {'weight': 1})]

In [112]:
# create network

output_dir = 'network efta countries/nx graph/with self-loops/'

for i in range(9):
    print(list_edgelist_list[i])

    edgelist = list_edgelist_list[i]

    # save graphs
    create_network_nx(list_edgelist_list[i], {}, 'undirected', output_dir + 'network_' + str(i+1) + '.graphml')

[('fr', 'gb', {'weight': 944}), ('de', 'fr', {'weight': 806}), ('fr', 'fr', {'weight': 732}), ('de', 'gb', {'weight': 727}), ('fr', 'it', {'weight': 692}), ('de', 'it', {'weight': 443}), ('gb', 'gb', {'weight': 443}), ('de', 'de', {'weight': 417}), ('gb', 'it', {'weight': 416}), ('gb', 'nl', {'weight': 374}), ('be', 'fr', {'weight': 374}), ('it', 'it', {'weight': 302}), ('fr', 'nl', {'weight': 289}), ('de', 'nl', {'weight': 268}), ('be', 'de', {'weight': 259}), ('be', 'gb', {'weight': 230}), ('dk', 'gb', {'weight': 212}), ('es', 'fr', {'weight': 195}), ('it', 'nl', {'weight': 176}), ('de', 'dk', {'weight': 165}), ('gb', 'ie', {'weight': 156}), ('be', 'it', {'weight': 138}), ('be', 'nl', {'weight': 133}), ('es', 'gb', {'weight': 132}), ('de', 'es', {'weight': 125}), ('fr', 'ie', {'weight': 121}), ('fr', 'gr', {'weight': 121}), ('dk', 'fr', {'weight': 120}), ('be', 'be', {'weight': 117}), ('gb', 'gr', {'weight': 110}), ('de', 'gr', {'weight': 108}), ('nl', 'nl', {'weight': 108}), ('gb', 'pt', {'weight': 107}), ('de', 'ie', {'weight': 103}), ('es', 'it', {'weight': 99}), ('dk', 'nl', {'weight': 97}), ('fr', 'pt', {'weight': 90}), ('dk', 'it', {'weight': 84}), ('de', 'pt', {'weight': 80}), ('gr', 'it', {'weight': 74}), ('be', 'dk', {'weight': 73}), ('es', 'es', {'weight': 70}), ('es', 'pt', {'weight': 70}), ('ie', 'it', {'weight': 68}), ('ie', 'nl', {'weight': 63}), ('dk', 'dk', {'weight': 62}), ('be', 'ie', {'weight': 60}), ('es', 'nl', {'weight': 60}), ('gr', 'nl', {'weight': 58}), ('be', 'es', {'weight': 50}), ('it', 'pt', {'weight': 47}), ('dk', 'es', {'weight': 45}), ('dk', 'ie', {'weight': 44}), ('nl', 'pt', {'weight': 40}), ('es', 'ie', {'weight': 39}), ('be', 'pt', {'weight': 39}), ('dk', 'gr', {'weight': 39}), ('pt', 'pt', {'weight': 38}), ('be', 'gr', {'weight': 36}), ('es', 'gr', {'weight': 35}), ('ie', 'ie', {'weight': 30}), ('ie', 'pt', {'weight': 27}), ('gr', 'gr', {'weight': 27}), ('dk', 'pt', {'weight': 26}), ('gr', 'pt', {'weight': 24}), ('gr', 'ie', {'weight': 22}), ('fr', 'se', {'weight': 18}), ('gb', 'se', {'weight': 17}), ('dk', 'se', {'weight': 17}), ('ch', 'fr', {'weight': 16}), ('nl', 'se', {'weight': 16}), ('de', 'se', {'weight': 13}), ('fi', 'gb', {'weight': 13}), ('it', 'se', {'weight': 12}), ('gr', 'se', {'weight': 12}), ('es', 'se', {'weight': 11}), ('be', 'se', {'weight': 11}), ('pt', 'se', {'weight': 10}), ('ch', 'gb', {'weight': 10}), ('ie', 'se', {'weight': 10}), ('gb', 'lu', {'weight': 9}), ('fi', 'fr', {'weight': 8}), ('ch', 'nl', {'weight': 8}), ('gb', 'no', {'weight': 7}), ('fr', 'no', {'weight': 7}), ('fi', 'se', {'weight': 6}), ('be', 'lu', {'weight': 5}), ('dk', 'fi', {'weight': 5}), ('fi', 'fi', {'weight': 5}), ('de', 'fi', {'weight': 4}), ('fi', 'nl', {'weight': 4}), ('at', 'de', {'weight': 4}), ('de', 'lu', {'weight': 3}), ('fr', 'lu', {'weight': 3}), ('ch', 'it', {'weight': 3}), ('at', 'fr', {'weight': 3}), ('ch', 'es', {'weight': 3}), ('at', 'nl', {'weight': 3}), ('it', 'no', {'weight': 3}), ('de', 'no', {'weight': 2}), ('be', 'ch', {'weight': 2}), ('no', 'pt', {'weight': 2}), ('fi', 'gr', {'weight': 2}), ('nl', 'no', {'weight': 2}), ('dk', 'no', {'weight': 2}), ('es', 'no', {'weight': 2}), ('fi', 'no', {'weight': 2}), ('ch', 'ie', {'weight': 1}), ('at', 'gr', {'weight': 1}), ('ch', 'dk', {'weight': 1}), ('at', 'it', {'weight': 1}), ('fi', 'it', {'weight': 1}), ('ch', 'gr', {'weight': 1}), ('es', 'fi', {'weight': 1}), ('at', 'be', {'weight': 1}), ('ch', 'de', {'weight': 1}), ('at', 'dk', {'weight': 1}), ('gr', 'no', {'weight': 1}), ('at', 'ch', {'weight': 1}), ('at', 'ie', {'weight': 1}), ('se', 'se', {'weight': 1}), ('no', 'no', {'weight': 1}), ('be', 'no', {'weight': 1}), ('lu', 'lu', {'weight': 1}), ('no', 'se', {'weight': 1})]
Network created
[('de', 'fr', {'weight': 4587}), ('de', 'gb', {'weight': 4052}), ('fr', 'gb', {'weight': 3971}), ('fr', 'it', {'weight': 2807}), ('de', 'de', {'weight': 2732}), ('fr', 'fr', {'weight': 2702}), ('de', 'it', {'weight': 2527}), ('de', 'nl', {'weight': 2278}), ('gb', 'it', {'weight': 2101}), ('gb', 'nl', {'weight': 1998}), ('es', 'fr', {'weight': 1993}), ('gb', 'gb', {'weight': 1935}), ('fr', 'nl', {'weight': 1869}), ('be', 'fr', {'weight': 1693}), ('de', 'es', {'weight': 1643}), ('be', 'de', {'weight': 1579}), ('es', 'gb', {'weight': 1470}), ('es', 'it', {'weight': 1261}), ('be', 'gb', {'weight': 1251}), ('it', 'it', {'weight': 1209}), ('de', 'dk', {'weight': 1137}), ('it', 'nl', {'weight': 1074}), ('dk', 'gb', {'weight': 970}), ('dk', 'fr', {'weight': 865}), ('fr', 'gr', {'weight': 855}), ('be', 'nl', {'weight': 838}), ('gb', 'gr', {'weight': 826}), ('be', 'it', {'weight': 806}), ('es', 'nl', {'weight': 795}), ('de', 'gr', {'weight': 776}), ('fr', 'pt', {'weight': 771}), ('nl', 'nl', {'weight': 711}), ('gb', 'ie', {'weight': 665}), ('dk', 'nl', {'weight': 640}), ('gb', 'pt', {'weight': 634}), ('de', 'pt', {'weight': 624}), ('be', 'es', {'weight': 600}), ('gr', 'it', {'weight': 590}), ('es', 'es', {'weight': 587}), ('de', 'ie', {'weight': 567}), ('gb', 'se', {'weight': 556}), ('fr', 'ie', {'weight': 545}), ('dk', 'it', {'weight': 531}), ('de', 'se', {'weight': 529}), ('it', 'pt', {'weight': 483}), ('es', 'pt', {'weight': 464}), ('be', 'dk', {'weight': 462}), ('fr', 'se', {'weight': 443}), ('dk', 'es', {'weight': 428}), ('be', 'be', {'weight': 407}), ('es', 'gr', {'weight': 394}), ('ie', 'it', {'weight': 367}), ('ch', 'de', {'weight': 352}), ('ie', 'nl', {'weight': 340}), ('gr', 'nl', {'weight': 337}), ('nl', 'pt', {'weight': 335}), ('ch', 'fr', {'weight': 314}), ('be', 'gr', {'weight': 310}), ('nl', 'se', {'weight': 283}), ('es', 'ie', {'weight': 265}), ('it', 'se', {'weight': 254}), ('be', 'pt', {'weight': 253}), ('de', 'fi', {'weight': 245}), ('dk', 'dk', {'weight': 242}), ('fi', 'gb', {'weight': 230}), ('ch', 'gb', {'weight': 230}), ('be', 'ie', {'weight': 229}), ('dk', 'gr', {'weight': 221}), ('gr', 'gr', {'weight': 213}), ('de', 'no', {'weight': 213}), ('gr', 'pt', {'weight': 208}), ('dk', 'pt', {'weight': 201}), ('ch', 'it', {'weight': 197}), ('es', 'se', {'weight': 191}), ('fi', 'fr', {'weight': 190}), ('pt', 'pt', {'weight': 189}), ('ch', 'nl', {'weight': 189}), ('dk', 'ie', {'weight': 183}), ('be', 'se', {'weight': 177}), ('gb', 'no', {'weight': 166}), ('dk', 'se', {'weight': 158}), ('fi', 'it', {'weight': 155}), ('fr', 'no', {'weight': 148}), ('fi', 'nl', {'weight': 141}), ('gr', 'ie', {'weight': 140}), ('ch', 'es', {'weight': 140}), ('ie', 'pt', {'weight': 134}), ('es', 'fi', {'weight': 123}), ('be', 'ch', {'weight': 122}), ('pt', 'se', {'weight': 104}), ('ie', 'ie', {'weight': 102}), ('be', 'fi', {'weight': 98}), ('nl', 'no', {'weight': 96}), ('dk', 'fi', {'weight': 92}), ('it', 'no', {'weight': 91}), ('gr', 'se', {'weight': 90}), ('at', 'de', {'weight': 89}), ('ch', 'dk', {'weight': 87}), ('ie', 'se', {'weight': 86}), ('at', 'fr', {'weight': 84}), ('se', 'se', {'weight': 82}), ('at', 'gb', {'weight': 74}), ('ch', 'se', {'weight': 68}), ('ch', 'pt', {'weight': 64}), ('es', 'no', {'weight': 62}), ('ch', 'gr', {'weight': 62}), ('fi', 'se', {'weight': 60}), ('fi', 'pt', {'weight': 59}), ('ch', 'ie', {'weight': 57}), ('be', 'no', {'weight': 55}), ('fi', 'gr', {'weight': 53}), ('no', 'se', {'weight': 53}), ('at', 'it', {'weight': 49}), ('dk', 'no', {'weight': 48}), ('fi', 'ie', {'weight': 45}), ('de', 'lu', {'weight': 41}), ('fr', 'lu', {'weight': 41}), ('ch', 'fi', {'weight': 39}), ('ch', 'ch', {'weight': 37}), ('gr', 'no', {'weight': 34}), ('be', 'lu', {'weight': 33}), ('at', 'nl', {'weight': 29}), ('at', 'es', {'weight': 26}), ('fi', 'no', {'weight': 25}), ('it', 'lu', {'weight': 25}), ('no', 'no', {'weight': 25}), ('gb', 'lu', {'weight': 21}), ('at', 'be', {'weight': 21}), ('ch', 'no', {'weight': 20}), ('fi', 'fi', {'weight': 19}), ('lu', 'nl', {'weight': 19}), ('no', 'pt', {'weight': 17}), ('es', 'lu', {'weight': 17}), ('at', 'gr', {'weight': 16}), ('dk', 'lu', {'weight': 13}), ('at', 'ie', {'weight': 12}), ('ie', 'no', {'weight': 12}), ('ie', 'lu', {'weight': 11}), ('at', 'se', {'weight': 11}), ('at', 'pt', {'weight': 11}), ('lu', 'pt', {'weight': 11}), ('at', 'dk', {'weight': 10}), ('gr', 'lu', {'weight': 10}), ('ch', 'lu', {'weight': 9}), ('lu', 'se', {'weight': 8}), ('at', 'at', {'weight': 8}), ('at', 'no', {'weight': 6}), ('fr', 'is', {'weight': 4}), ('de', 'li', {'weight': 4}), ('at', 'ch', {'weight': 4}), ('is', 'it', {'weight': 3}), ('fi', 'lu', {'weight': 3}), ('is', 'se', {'weight': 2}), ('at', 'fi', {'weight': 2}), ('de', 'is', {'weight': 2}), ('gr', 'is', {'weight': 2}), ('fr', 'li', {'weight': 2}), ('gb', 'is', {'weight': 2}), ('it', 'li', {'weight': 1}), ('li', 'nl', {'weight': 1}), ('es', 'li', {'weight': 1}), ('is', 'pt', {'weight': 1}), ('be', 'is', {'weight': 1}), ('is', 'is', {'weight': 1})]
Network created
[('de', 'fr', {'weight': 7255}), ('de', 'gb', {'weight': 7039}), ('fr', 'gb', {'weight': 6730}), ('fr', 'it', {'weight': 4787}), ('fr', 'fr', {'weight': 4732}), ('de', 'de', {'weight': 4564}), ('de', 'it', {'weight': 4079}), ('gb', 'it', {'weight': 3915}), ('gb', 'gb', {'weight': 3798}), ('es', 'fr', {'weight': 3199}), ('gb', 'nl', {'weight': 3180}), ('de', 'nl', {'weight': 3141}), ('fr', 'nl', {'weight': 2678}), ('es', 'gb', {'weight': 2670}), ('de', 'es', {'weight': 2643}), ('it', 'it', {'weight': 2351}), ('be', 'fr', {'weight': 2169}), ('es', 'it', {'weight': 2153}), ('be', 'de', {'weight': 1977}), ('be', 'gb', {'weight': 1735}), ('gb', 'gr', {'weight': 1730}), ('de', 'gr', {'weight': 1723}), ('fr', 'gr', {'weight': 1601}), ('dk', 'gb', {'weight': 1518}), ('it', 'nl', {'weight': 1425}), ('de', 'dk', {'weight': 1404}), ('gr', 'it', {'weight': 1283}), ('fr', 'pt', {'weight': 1257}), ('gb', 'pt', {'weight': 1240}), ('es', 'es', {'weight': 1224}), ('dk', 'fr', {'weight': 1158}), ('de', 'se', {'weight': 1150}), ('es', 'nl', {'weight': 1141}), ('be', 'it', {'weight': 1083}), ('gb', 'ie', {'weight': 1082}), ('de', 'pt', {'weight': 1075}), ('gb', 'se', {'weight': 1071}), ('fr', 'se', {'weight': 1016}), ('nl', 'nl', {'weight': 958}), ('be', 'nl', {'weight': 957}), ('gr', 'gr', {'weight': 879}), ('de', 'ie', {'weight': 871}), ('fr', 'ie', {'weight': 849}), ('es', 'gr', {'weight': 843}), ('it', 'pt', {'weight': 831}), ('be', 'es', {'weight': 793}), ('es', 'pt', {'weight': 791}), ('dk', 'nl', {'weight': 758}), ('ch', 'de', {'weight': 744}), ('ch', 'fr', {'weight': 727}), ('gr', 'nl', {'weight': 694}), ('be', 'be', {'weight': 677}), ('dk', 'it', {'weight': 669}), ('ch', 'gb', {'weight': 597}), ('gb', 'no', {'weight': 583}), ('ie', 'it', {'weight': 548}), ('nl', 'se', {'weight': 548}), ('de', 'fi', {'weight': 546}), ('it', 'se', {'weight': 536}), ('nl', 'pt', {'weight': 521}), ('dk', 'es', {'weight': 510}), ('be', 'gr', {'weight': 487}), ('de', 'no', {'weight': 480}), ('ie', 'nl', {'weight': 477}), ('fi', 'gb', {'weight': 464}), ('fr', 'no', {'weight': 464}), ('ch', 'it', {'weight': 455}), ('gr', 'pt', {'weight': 445}), ('es', 'ie', {'weight': 440}), ('at', 'de', {'weight': 426}), ('fi', 'fr', {'weight': 409}), ('be', 'pt', {'weight': 390}), ('be', 'dk', {'weight': 383}), ('dk', 'gr', {'weight': 379}), ('dk', 'dk', {'weight': 357}), ('es', 'se', {'weight': 345}), ('be', 'se', {'weight': 344}), ('pt', 'pt', {'weight': 344}), ('dk', 'se', {'weight': 340}), ('ch', 'nl', {'weight': 321}), ('at', 'fr', {'weight': 310}), ('be', 'ie', {'weight': 294}), ('at', 'gb', {'weight': 279}), ('dk', 'pt', {'weight': 272}), ('nl', 'no', {'weight': 269}), ('gr', 'ie', {'weight': 265}), ('dk', 'ie', {'weight': 265}), ('ch', 'es', {'weight': 263}), ('fi', 'nl', {'weight': 261}), ('fi', 'it', {'weight': 254}), ('at', 'it', {'weight': 244}), ('it', 'no', {'weight': 236}), ('ie', 'pt', {'weight': 234}), ('dk', 'no', {'weight': 232}), ('gr', 'se', {'weight': 215}), ('be', 'ch', {'weight': 213}), ('se', 'se', {'weight': 209}), ('es', 'no', {'weight': 196}), ('es', 'fi', {'weight': 195}), ('ie', 'ie', {'weight': 188}), ('dk', 'fi', {'weight': 170}), ('ie', 'se', {'weight': 167}), ('pt', 'se', {'weight': 154}), ('at', 'nl', {'weight': 146}), ('ch', 'gr', {'weight': 143}), ('fi', 'gr', {'weight': 141}), ('no', 'se', {'weight': 139}), ('be', 'no', {'weight': 132}), ('ch', 'dk', {'weight': 131}), ('fi', 'se', {'weight': 126}), ('ch', 'se', {'weight': 122}), ('be', 'fi', {'weight': 122}), ('no', 'pt', {'weight': 117}), ('at', 'es', {'weight': 116}), ('fi', 'fi', {'weight': 112}), ('gr', 'no', {'weight': 110}), ('fi', 'ie', {'weight': 107}), ('ch', 'pt', {'weight': 100}), ('no', 'no', {'weight': 92}), ('at', 'gr', {'weight': 91}), ('ch', 'ie', {'weight': 90}), ('ie', 'no', {'weight': 89}), ('ch', 'fi', {'weight': 87}), ('at', 'se', {'weight': 84}), ('fi', 'pt', {'weight': 83}), ('at', 'be', {'weight': 81}), ('fi', 'no', {'weight': 72}), ('ch', 'no', {'weight': 70}), ('at', 'dk', {'weight': 69}), ('ch', 'ch', {'weight': 61}), ('at', 'ch', {'weight': 50}), ('at', 'pt', {'weight': 49}), ('at', 'fi', {'weight': 45}), ('at', 'ie', {'weight': 44}), ('de', 'lu', {'weight': 43}), ('at', 'no', {'weight': 42}), ('gb', 'is', {'weight': 37}), ('fr', 'lu', {'weight': 36}), ('de', 'is', {'weight': 35}), ('gb', 'pl', {'weight': 32}), ('at', 'at', {'weight': 32}), ('de', 'pl', {'weight': 30}), ('dk', 'is', {'weight': 30}), ('de', 'hu', {'weight': 28}), ('be', 'lu', {'weight': 27}), ('gb', 'hu', {'weight': 27}), ('gb', 'lu', {'weight': 26}), ('fr', 'is', {'weight': 24}), ('gr', 'hu', {'weight': 20}), ('es', 'is', {'weight': 20}), ('es', 'pl', {'weight': 19}), ('gr', 'pl', {'weight': 19}), ('is', 'no', {'weight': 19}), ('is', 'nl', {'weight': 18}), ('hu', 'it', {'weight': 17}), ('gb', 'ro', {'weight': 17}), ('it', 'pl', {'weight': 16}), ('is', 'it', {'weight': 16}), ('fr', 'pl', {'weight': 16}), ('is', 'se', {'weight': 15}), ('gr', 'lu', {'weight': 15}), ('es', 'hu', {'weight': 15}), ('pl', 'pt', {'weight': 15}), ('it', 'lu', {'weight': 14}), ('hu', 'pt', {'weight': 14}), ('lu', 'nl', {'weight': 14}), ('fr', 'hu', {'weight': 14}), ('es', 'lu', {'weight': 14}), ('ie', 'is', {'weight': 13}), ('nl', 'pl', {'weight': 13}), ('is', 'pt', {'weight': 11}), ('ie', 'lu', {'weight': 10}), ('gr', 'is', {'weight': 10}), ('ch', 'lu', {'weight': 10}), ('de', 'ro', {'weight': 9}), ('hu', 'pl', {'weight': 9}), ('pl', 'se', {'weight': 9}), ('dk', 'lu', {'weight': 9}), ('de', 'sk', {'weight': 8}), ('hu', 'nl', {'weight': 8}), ('gr', 'ro', {'weight': 8}), ('gb', 'sk', {'weight': 8}), ('be', 'is', {'weight': 7}), ('no', 'pl', {'weight': 7}), ('fr', 'ro', {'weight': 7}), ('is', 'is', {'weight': 7}), ('fi', 'is', {'weight': 7}), ('gr', 'sk', {'weight': 6}), ('be', 'pl', {'weight': 6}), ('it', 'si', {'weight': 6}), ('hu', 'se', {'weight': 6}), ('at', 'lu', {'weight': 6}), ('es', 'ro', {'weight': 6}), ('nl', 'ro', {'weight': 5}), ('it', 'ro', {'weight': 5}), ('dk', 'hu', {'weight': 5}), ('es', 'sk', {'weight': 5}), ('lu', 'se', {'weight': 5}), ('lu', 'pt', {'weight': 5}), ('ie', 'pl', {'weight': 4}), ('fr', 'si', {'weight': 4}), ('pt', 'ro', {'weight': 4}), ('de', 'si', {'weight': 4}), ('it', 'sk', {'weight': 4}), ('lu', 'no', {'weight': 4}), ('gb', 'si', {'weight': 4}), ('be', 'hu', {'weight': 4}), ('pt', 'sk', {'weight': 4}), ('cy', 'fr', {'weight': 4}), ('fr', 'sk', {'weight': 4}), ('be', 'ro', {'weight': 4}), ('fi', 'hu', {'weight': 4}), ('dk', 'pl', {'weight': 4}), ('fi', 'ro', {'weight': 3}), ('dk', 'ro', {'weight': 3}), ('ch', 'is', {'weight': 3}), ('hu', 'sk', {'weight': 3}), ('cz', 'no', {'weight': 3}), ('cz', 'es', {'weight': 3}), ('hu', 'hu', {'weight': 3}), ('cy', 'gr', {'weight': 3}), ('ro', 'se', {'weight': 3}), ('pl', 'ro', {'weight': 3}), ('pl', 'pl', {'weight': 3}), ('fi', 'pl', {'weight': 3}), ('pl', 'sk', {'weight': 3}), ('hu', 'ie', {'weight': 3}), ('at', 'pl', {'weight': 3}), ('hu', 'no', {'weight': 3}), ('hu', 'ro', {'weight': 3}), ('se', 'sk', {'weight': 2}), ('be', 'si', {'weight': 2}), ('cz', 'gb', {'weight': 2}), ('at', 'cz', {'weight': 2}), ('cy', 'gb', {'weight': 2}), ('at', 'is', {'weight': 2}), ('cz', 'it', {'weight': 2}), ('fi', 'lu', {'weight': 2}), ('bg', 'fr', {'weight': 2}), ('ie', 'ro', {'weight': 2}), ('nl', 'si', {'weight': 2}), ('nl', 'sk', {'weight': 2}), ('ch', 'pl', {'weight': 2}), ('pt', 'si', {'weight': 2}), ('ie', 'sk', {'weight': 1}), ('fi', 'sk', {'weight': 1}), ('gr', 'si', {'weight': 1}), ('is', 'lu', {'weight': 1}), ('be', 'cy', {'weight': 1}), ('cy', 'pt', {'weight': 1}), ('ee', 'pl', {'weight': 1}), ('cz', 'fr', {'weight': 1}), ('bg', 'es', {'weight': 1}), ('at', 'hu', {'weight': 1}), ('cz', 'de', {'weight': 1}), ('lu', 'lu', {'weight': 1}), ('ee', 'se', {'weight': 1}), ('cz', 'dk', {'weight': 1}), ('ie', 'si', {'weight': 1}), ('cz', 'hu', {'weight': 1}), ('es', 'si', {'weight': 1}), ('dk', 'sk', {'weight': 1}), ('no', 'ro', {'weight': 1}), ('ee', 'nl', {'weight': 1}), ('cy', 'nl', {'weight': 1}), ('cz', 'pl', {'weight': 1}), ('at', 'si', {'weight': 1}), ('de', 'ee', {'weight': 1}), ('cz', 'pt', {'weight': 1}), ('ro', 'sk', {'weight': 1}), ('at', 'cy', {'weight': 1}), ('cz', 'nl', {'weight': 1}), ('cy', 'es', {'weight': 1}), ('be', 'sk', {'weight': 1}), ('se', 'si', {'weight': 1}), ('no', 'sk', {'weight': 1})]
Network created

In [114]:
# create networks without self-loops

input_dir = 'network efta countries/nx graph/with self-loops/'
output_dir = 'network efta countries/nx graph/without self-loops/'

for i in range(1, 10):

    g = nx.read_graphml(input_dir + 'network_' + str(i) + '.graphml')
    g.remove_edges_from(nx.selfloop_edges(g))

    nx.write_graphml(g, output_dir + 'network_' + str(i) + '.graphml')

In [116]:
# create edgelist without self-loops

input_dir = 'network efta countries/nx graph/without self-loops/'
output_dir = 'network efta countries/edgelist/without self-loops/'

for i in range(1, 10):
    
    g = nx.read_graphml(input_dir + 'network_' + str(i) + '.graphml')
    edges = list(g.edges(data=True))
    edge_df = list_edgelist_to_df_edgelist(edges)

    edge_df.to_csv(output_dir + 'edgelist_' + str(i) + '.csv')

In [117]:
# create edgelist with weights without self-loops

input_dir = 'network efta countries/edgelist/without self-loops/'
output_dir = 'network efta countries/edgelist weighted/without self-loops/'

for i in range(1, 10):

    edgelist = pl.read_csv(input_dir + 'edgelist_' + str(i) + '.csv')

    # normalize pairs by sorting (min, max)
    edgelist_weighted_undirected = edgelist.with_columns([
        pl.min_horizontal('source', 'target').alias('node1'),
        pl.max_horizontal('source', 'target').alias('node2'),
    ])

    # group by normalized pair and sum weights
    edgelist_weighted_undirected_final = (
        edgelist_weighted_undirected.group_by(['node1', 'node2'])
                                              .agg(pl.col('weight').sum().alias('total_weight'))
                                              .sort('total_weight', descending=True)
                                              .rename({'node1': 'source', 'node2': 'target', 'total_weight': 'weight'})
    )

    edgelist_weighted_undirected_final.write_csv(output_dir + 'edgelist_weighted_' + str(i) + '.csv')

In [99]:
g = gt.load_graph('network efta countries/nx graph/without self-loops/network_NEW_9.graphml')
for v in g.vertices():
    print(f"Node {int(v)}:")
    for prop_name, prop in g.vp.items():
        print(f"  {prop_name}: {prop[v]}")
print("Edge Properties:")
for prop_name, prop_map in g.ep.items():
    print(f"Property: {prop_name}")
    for e in g.edges():
        print(f"Edge {e}: {prop_name} = {prop_map[e]}")

Node 0:
  _graphml_vertex_id: es
Node 1:
  _graphml_vertex_id: it
Node 2:
  _graphml_vertex_id: de
Node 3:
  _graphml_vertex_id: fr
Node 4:
  _graphml_vertex_id: nl
Node 5:
  _graphml_vertex_id: be
Node 6:
  _graphml_vertex_id: gr
Node 7:
  _graphml_vertex_id: gb
Node 8:
  _graphml_vertex_id: at
Node 9:
  _graphml_vertex_id: pt
Node 10:
  _graphml_vertex_id: ch
Node 11:
  _graphml_vertex_id: se
Node 12:
  _graphml_vertex_id: fi
Node 13:
  _graphml_vertex_id: dk
Node 14:
  _graphml_vertex_id: pl
Node 15:
  _graphml_vertex_id: no
Node 16:
  _graphml_vertex_id: ie
Node 17:
  _graphml_vertex_id: cz
Node 18:
  _graphml_vertex_id: si
Node 19:
  _graphml_vertex_id: ro
Node 20:
  _graphml_vertex_id: cy
Node 21:
  _graphml_vertex_id: hu
Node 22:
  _graphml_vertex_id: ee
Node 23:
  _graphml_vertex_id: bg
Node 24:
  _graphml_vertex_id: hr
Node 25:
  _graphml_vertex_id: lt
Node 26:
  _graphml_vertex_id: sk
Node 27:
  _graphml_vertex_id: lu
Node 28:
  _graphml_vertex_id: lv
Node 29:
  _graphml_vertex_id: mt
Node 30:
  _graphml_vertex_id: is
Node 31:
  _graphml_vertex_id: li
Edge Properties:
Property: _graphml_edge_id
Edge (0, 1): _graphml_edge_id =
Edge (0, 2): _graphml_edge_id =
Edge (0, 3): _graphml_edge_id =
Edge (0, 5): _graphml_edge_id =
Edge (0, 6): _graphml_edge_id =
Edge (0, 4): _graphml_edge_id =
Edge (0, 7): _graphml_edge_id =
Edge (0, 9): _graphml_edge_id =
Edge (0, 8): _graphml_edge_id =
Edge (0, 11): _graphml_edge_id =
Edge (0, 10): _graphml_edge_id =
Edge (0, 12): _graphml_edge_id =
Edge (0, 13): _graphml_edge_id =
Edge (0, 14): _graphml_edge_id =
Edge (0, 15): _graphml_edge_id =
Edge (0, 16): _graphml_edge_id =
Edge (0, 17): _graphml_edge_id =
Edge (0, 18): _graphml_edge_id =
Edge (0, 19): _graphml_edge_id =
Edge (0, 21): _graphml_edge_id =
Edge (0, 20): _graphml_edge_id =
Edge (0, 22): _graphml_edge_id =
Edge (0, 23): _graphml_edge_id =
Edge (0, 25): _graphml_edge_id =
Edge (0, 24): _graphml_edge_id =
Edge (0, 26): _graphml_edge_id =
Edge (0, 27): _graphml_edge_id =
Edge (0, 28): _graphml_edge_id =
Edge (0, 29): _graphml_edge_id =
Edge (0, 30): _graphml_edge_id =
Edge (0, 31): _graphml_edge_id =
Edge (1, 2): _graphml_edge_id =
Edge (1, 3): _graphml_edge_id =
Edge (1, 4): _graphml_edge_id =
Edge (1, 5): _graphml_edge_id =
Edge (1, 6): _graphml_edge_id =
Edge (1, 7): _graphml_edge_id =
Edge (1, 8): _graphml_edge_id =
Edge (1, 9): _graphml_edge_id =
Edge (1, 11): _graphml_edge_id =
Edge (1, 10): _graphml_edge_id =
Edge (1, 12): _graphml_edge_id =
Edge (1, 14): _graphml_edge_id =
Edge (1, 13): _graphml_edge_id =
Edge (1, 15): _graphml_edge_id =
Edge (1, 18): _graphml_edge_id =
Edge (1, 16): _graphml_edge_id =
Edge (1, 17): _graphml_edge_id =
Edge (1, 19): _graphml_edge_id =
Edge (1, 20): _graphml_edge_id =
Edge (1, 21): _graphml_edge_id =
Edge (1, 24): _graphml_edge_id =
Edge (1, 23): _graphml_edge_id =
Edge (1, 22): _graphml_edge_id =
Edge (1, 25): _graphml_edge_id =
Edge (1, 26): _graphml_edge_id =
Edge (1, 27): _graphml_edge_id =
Edge (1, 28): _graphml_edge_id =
Edge (1, 29): _graphml_edge_id =
Edge (1, 30): _graphml_edge_id =
Edge (1, 31): _graphml_edge_id =
Edge (2, 3): _graphml_edge_id =
Edge (2, 4): _graphml_edge_id =
Edge (2, 5): _graphml_edge_id =
Edge (2, 7): _graphml_edge_id =
Edge (2, 8): _graphml_edge_id =
Edge (2, 6): _graphml_edge_id =
Edge (2, 10): _graphml_edge_id =
Edge (2, 11): _graphml_edge_id =
Edge (2, 12): _graphml_edge_id =
Edge (2, 9): _graphml_edge_id =
Edge (2, 13): _graphml_edge_id =
Edge (2, 15): _graphml_edge_id =
Edge (2, 14): _graphml_edge_id =
Edge (2, 17): _graphml_edge_id =
Edge (2, 16): _graphml_edge_id =
Edge (2, 18): _graphml_edge_id =
Edge (2, 19): _graphml_edge_id =
Edge (2, 21): _graphml_edge_id =
Edge (2, 20): _graphml_edge_id =
Edge (2, 24): _graphml_edge_id =
Edge (2, 22): _graphml_edge_id =
Edge (2, 25): _graphml_edge_id =
Edge (2, 23): _graphml_edge_id =
Edge (2, 26): _graphml_edge_id =
Edge (2, 27): _graphml_edge_id =
Edge (2, 28): _graphml_edge_id =
Edge (2, 29): _graphml_edge_id =
Edge (2, 30): _graphml_edge_id =
Edge (2, 31): _graphml_edge_id =
Edge (3, 4): _graphml_edge_id =
Edge (3, 5): _graphml_edge_id =
Edge (3, 7): _graphml_edge_id =
Edge (3, 6): _graphml_edge_id =
Edge (3, 8): _graphml_edge_id =
Edge (3, 10): _graphml_edge_id =
Edge (3, 11): _graphml_edge_id =
Edge (3, 9): _graphml_edge_id =
Edge (3, 12): _graphml_edge_id =
Edge (3, 14): _graphml_edge_id =
Edge (3, 13): _graphml_edge_id =
Edge (3, 15): _graphml_edge_id =
Edge (3, 17): _graphml_edge_id =
Edge (3, 16): _graphml_edge_id =
Edge (3, 19): _graphml_edge_id =
Edge (3, 18): _graphml_edge_id =
Edge (3, 21): _graphml_edge_id =
Edge (3, 24): _graphml_edge_id =
Edge (3, 20): _graphml_edge_id =
Edge (3, 26): _graphml_edge_id =
Edge (3, 23): _graphml_edge_id =
Edge (3, 22): _graphml_edge_id =
Edge (3, 25): _graphml_edge_id =
Edge (3, 28): _graphml_edge_id =
Edge (3, 27): _graphml_edge_id =
Edge (3, 30): _graphml_edge_id =
Edge (3, 29): _graphml_edge_id =
Edge (3, 31): _graphml_edge_id =
Edge (4, 5): _graphml_edge_id =
Edge (4, 7): _graphml_edge_id =
Edge (4, 6): _graphml_edge_id =
Edge (4, 8): _graphml_edge_id =
Edge (4, 10): _graphml_edge_id =
Edge (4, 11): _graphml_edge_id =
Edge (4, 12): _graphml_edge_id =
Edge (4, 13): _graphml_edge_id =
Edge (4, 9): _graphml_edge_id =
Edge (4, 15): _graphml_edge_id =
Edge (4, 14): _graphml_edge_id =
Edge (4, 16): _graphml_edge_id =
Edge (4, 17): _graphml_edge_id =
Edge (4, 21): _graphml_edge_id =
Edge (4, 19): _graphml_edge_id =
Edge (4, 18): _graphml_edge_id =
Edge (4, 20): _graphml_edge_id =
Edge (4, 22): _graphml_edge_id =
Edge (4, 26): _graphml_edge_id =
Edge (4, 24): _graphml_edge_id =
Edge (4, 25): _graphml_edge_id =
Edge (4, 23): _graphml_edge_id =
Edge (4, 28): _graphml_edge_id =
Edge (4, 27): _graphml_edge_id =
Edge (4, 29): _graphml_edge_id =
Edge (4, 30): _graphml_edge_id =
Edge (5, 6): _graphml_edge_id =
Edge (5, 7): _graphml_edge_id =
Edge (5, 8): _graphml_edge_id =
Edge (5, 9): _graphml_edge_id =
Edge (5, 11): _graphml_edge_id =
Edge (5, 12): _graphml_edge_id =
Edge (5, 10): _graphml_edge_id =
Edge (5, 13): _graphml_edge_id =
Edge (5, 15): _graphml_edge_id =
Edge (5, 14): _graphml_edge_id =
Edge (5, 16): _graphml_edge_id =
Edge (5, 17): _graphml_edge_id =
Edge (5, 18): _graphml_edge_id =
Edge (5, 19): _graphml_edge_id =
Edge (5, 21): _graphml_edge_id =
Edge (5, 22): _graphml_edge_id =
Edge (5, 20): _graphml_edge_id =
Edge (5, 25): _graphml_edge_id =
Edge (5, 23): _graphml_edge_id =
Edge (5, 24): _graphml_edge_id =
Edge (5, 27): _graphml_edge_id =
Edge (5, 26): _graphml_edge_id =
Edge (5, 28): _graphml_edge_id =
Edge (5, 29): _graphml_edge_id =
Edge (5, 30): _graphml_edge_id =
Edge (5, 31): _graphml_edge_id =
Edge (6, 7): _graphml_edge_id =
Edge (6, 9): _graphml_edge_id =
Edge (6, 20): _graphml_edge_id =
Edge (6, 10): _graphml_edge_id =
Edge (6, 8): _graphml_edge_id =
Edge (6, 12): _graphml_edge_id =
Edge (6, 11): _graphml_edge_id =
Edge (6, 15): _graphml_edge_id =
Edge (6, 14): _graphml_edge_id =
Edge (6, 13): _graphml_edge_id =
Edge (6, 19): _graphml_edge_id =
Edge (6, 16): _graphml_edge_id =
Edge (6, 18): _graphml_edge_id =
Edge (6, 17): _graphml_edge_id =
Edge (6, 23): _graphml_edge_id =
Edge (6, 27): _graphml_edge_id =
Edge (6, 21): _graphml_edge_id =
Edge (6, 25): _graphml_edge_id =
Edge (6, 24): _graphml_edge_id =
Edge (6, 22): _graphml_edge_id =
Edge (6, 28): _graphml_edge_id =
Edge (6, 26): _graphml_edge_id =
Edge (6, 29): _graphml_edge_id =
Edge (6, 30): _graphml_edge_id =
Edge (7, 10): _graphml_edge_id =
Edge (7, 11): _graphml_edge_id =
Edge (7, 9): _graphml_edge_id =
Edge (7, 8): _graphml_edge_id =
Edge (7, 13): _graphml_edge_id =
Edge (7, 12): _graphml_edge_id =
Edge (7, 15): _graphml_edge_id =
Edge (7, 16): _graphml_edge_id =
Edge (7, 14): _graphml_edge_id =
Edge (7, 17): _graphml_edge_id =
Edge (7, 18): _graphml_edge_id =
Edge (7, 19): _graphml_edge_id =
Edge (7, 21): _graphml_edge_id =
Edge (7, 20): _graphml_edge_id =
Edge (7, 22): _graphml_edge_id =
Edge (7, 23): _graphml_edge_id =
Edge (7, 25): _graphml_edge_id =
Edge (7, 24): _graphml_edge_id =
Edge (7, 26): _graphml_edge_id =
Edge (7, 27): _graphml_edge_id =
Edge (7, 28): _graphml_edge_id =
Edge (7, 30): _graphml_edge_id =
Edge (7, 29): _graphml_edge_id =
Edge (7, 31): _graphml_edge_id =
Edge (8, 11): _graphml_edge_id =
Edge (8, 12): _graphml_edge_id =
Edge (8, 10): _graphml_edge_id =
Edge (8, 14): _graphml_edge_id =
Edge (8, 9): _graphml_edge_id =
Edge (8, 13): _graphml_edge_id =
Edge (8, 17): _graphml_edge_id =
Edge (8, 15): _graphml_edge_id =
Edge (8, 19): _graphml_edge_id =
Edge (8, 18): _graphml_edge_id =
Edge (8, 21): _graphml_edge_id =
Edge (8, 16): _graphml_edge_id =
Edge (8, 24): _graphml_edge_id =
Edge (8, 26): _graphml_edge_id =
Edge (8, 23): _graphml_edge_id =
Edge (8, 20): _graphml_edge_id =
Edge (8, 22): _graphml_edge_id =
Edge (8, 25): _graphml_edge_id =
Edge (8, 28): _graphml_edge_id =
Edge (8, 27): _graphml_edge_id =
Edge (8, 29): _graphml_edge_id =
Edge (8, 30): _graphml_edge_id =
Edge (9, 12): _graphml_edge_id =
Edge (9, 13): _graphml_edge_id =
Edge (9, 15): _graphml_edge_id =
Edge (9, 11): _graphml_edge_id =
Edge (9, 10): _graphml_edge_id =
Edge (9, 14): _graphml_edge_id =
Edge (9, 16): _graphml_edge_id =
Edge (9, 19): _graphml_edge_id =
Edge (9, 17): _graphml_edge_id =
Edge (9, 18): _graphml_edge_id =
Edge (9, 20): _graphml_edge_id =
Edge (9, 21): _graphml_edge_id =
Edge (9, 24): _graphml_edge_id =
Edge (9, 23): _graphml_edge_id =
Edge (9, 22): _graphml_edge_id =
Edge (9, 27): _graphml_edge_id =
Edge (9, 26): _graphml_edge_id =
Edge (9, 25): _graphml_edge_id =
Edge (9, 28): _graphml_edge_id =
Edge (9, 30): _graphml_edge_id =
Edge (9, 29): _graphml_edge_id =
Edge (9, 31): _graphml_edge_id =
Edge (10, 11): _graphml_edge_id =
Edge (10, 12): _graphml_edge_id =
Edge (10, 13): _graphml_edge_id =
Edge (10, 15): _graphml_edge_id =
Edge (10, 14): _graphml_edge_id =
Edge (10, 17): _graphml_edge_id =
Edge (10, 16): _graphml_edge_id =
Edge (10, 18): _graphml_edge_id =
Edge (10, 19): _graphml_edge_id =
Edge (10, 20): _graphml_edge_id =
Edge (10, 21): _graphml_edge_id =
Edge (10, 22): _graphml_edge_id =
Edge (10, 25): _graphml_edge_id =
Edge (10, 23): _graphml_edge_id =
Edge (10, 27): _graphml_edge_id =
Edge (10, 24): _graphml_edge_id =
Edge (10, 26): _graphml_edge_id =
Edge (10, 28): _graphml_edge_id =
Edge (10, 29): _graphml_edge_id =
Edge (10, 30): _graphml_edge_id =
Edge (10, 31): _graphml_edge_id =
Edge (11, 12): _graphml_edge_id =
Edge (11, 13): _graphml_edge_id =
Edge (11, 15): _graphml_edge_id =
Edge (11, 14): _graphml_edge_id =
Edge (11, 17): _graphml_edge_id =
Edge (11, 16): _graphml_edge_id =
Edge (11, 18): _graphml_edge_id =
Edge (11, 21): _graphml_edge_id =
Edge (11, 19): _graphml_edge_id =
Edge (11, 22): _graphml_edge_id =
Edge (11, 25): _graphml_edge_id =
Edge (11, 24): _graphml_edge_id =
Edge (11, 23): _graphml_edge_id =
Edge (11, 20): _graphml_edge_id =
Edge (11, 28): _graphml_edge_id =
Edge (11, 26): _graphml_edge_id =
Edge (11, 27): _graphml_edge_id =
Edge (11, 30): _graphml_edge_id =
Edge (11, 29): _graphml_edge_id =
Edge (11, 31): _graphml_edge_id =
Edge (12, 15): _graphml_edge_id =
Edge (12, 13): _graphml_edge_id =
Edge (12, 14): _graphml_edge_id =
Edge (12, 17): _graphml_edge_id =
Edge (12, 22): _graphml_edge_id =
Edge (12, 16): _graphml_edge_id =
Edge (12, 18): _graphml_edge_id =
Edge (12, 19): _graphml_edge_id =
Edge (12, 21): _graphml_edge_id =
Edge (12, 25): _graphml_edge_id =
Edge (12, 20): _graphml_edge_id =
Edge (12, 28): _graphml_edge_id =
Edge (12, 24): _graphml_edge_id =
Edge (12, 23): _graphml_edge_id =
Edge (12, 26): _graphml_edge_id =
Edge (12, 27): _graphml_edge_id =
Edge (12, 30): _graphml_edge_id =
Edge (12, 29): _graphml_edge_id =
Edge (12, 31): _graphml_edge_id =
Edge (13, 15): _graphml_edge_id =
Edge (13, 14): _graphml_edge_id =
Edge (13, 16): _graphml_edge_id =
Edge (13, 17): _graphml_edge_id =
Edge (13, 18): _graphml_edge_id =
Edge (13, 22): _graphml_edge_id =
Edge (13, 19): _graphml_edge_id =
Edge (13, 21): _graphml_edge_id =
Edge (13, 24): _graphml_edge_id =
Edge (13, 25): _graphml_edge_id =
Edge (13, 20): _graphml_edge_id =
Edge (13, 28): _graphml_edge_id =
Edge (13, 23): _graphml_edge_id =
Edge (13, 26): _graphml_edge_id =
Edge (13, 27): _graphml_edge_id =
Edge (13, 30): _graphml_edge_id =
Edge (13, 29): _graphml_edge_id =
Edge (14, 15): _graphml_edge_id =
Edge (14, 17): _graphml_edge_id =
Edge (14, 16): _graphml_edge_id =
Edge (14, 19): _graphml_edge_id =
Edge (14, 21): _graphml_edge_id =
Edge (14, 18): _graphml_edge_id =
Edge (14, 28): _graphml_edge_id =
Edge (14, 26): _graphml_edge_id =
Edge (14, 25): _graphml_edge_id =
Edge (14, 23): _graphml_edge_id =
Edge (14, 24): _graphml_edge_id =
Edge (14, 22): _graphml_edge_id =
Edge (14, 20): _graphml_edge_id =
Edge (14, 27): _graphml_edge_id =
Edge (14, 29): _graphml_edge_id =
Edge (14, 30): _graphml_edge_id =
Edge (14, 31): _graphml_edge_id =
Edge (15, 16): _graphml_edge_id =
Edge (15, 17): _graphml_edge_id =
Edge (15, 18): _graphml_edge_id =
Edge (15, 22): _graphml_edge_id =
Edge (15, 19): _graphml_edge_id =
Edge (15, 21): _graphml_edge_id =
Edge (15, 20): _graphml_edge_id =
Edge (15, 25): _graphml_edge_id =
Edge (15, 23): _graphml_edge_id =
Edge (15, 24): _graphml_edge_id =
Edge (15, 26): _graphml_edge_id =
Edge (15, 28): _graphml_edge_id =
Edge (15, 30): _graphml_edge_id =
Edge (15, 27): _graphml_edge_id =
Edge (15, 29): _graphml_edge_id =
Edge (15, 31): _graphml_edge_id =
Edge (16, 19): _graphml_edge_id =
Edge (16, 17): _graphml_edge_id =
Edge (16, 20): _graphml_edge_id =
Edge (16, 18): _graphml_edge_id =
Edge (16, 21): _graphml_edge_id =
Edge (16, 22): _graphml_edge_id =
Edge (16, 23): _graphml_edge_id =
Edge (16, 25): _graphml_edge_id =
Edge (16, 24): _graphml_edge_id =
Edge (16, 26): _graphml_edge_id =
Edge (16, 27): _graphml_edge_id =
Edge (16, 28): _graphml_edge_id =
Edge (16, 29): _graphml_edge_id =
Edge (16, 30): _graphml_edge_id =
Edge (16, 31): _graphml_edge_id =
Edge (17, 26): _graphml_edge_id =
Edge (17, 19): _graphml_edge_id =
Edge (17, 21): _graphml_edge_id =
Edge (17, 18): _graphml_edge_id =
Edge (17, 22): _graphml_edge_id =
Edge (17, 25): _graphml_edge_id =
Edge (17, 24): _graphml_edge_id =
Edge (17, 28): _graphml_edge_id =
Edge (17, 23): _graphml_edge_id =
Edge (17, 20): _graphml_edge_id =
Edge (17, 27): _graphml_edge_id =
Edge (17, 29): _graphml_edge_id =
Edge (17, 30): _graphml_edge_id =
Edge (17, 31): _graphml_edge_id =
Edge (18, 24): _graphml_edge_id =
Edge (18, 19): _graphml_edge_id =
Edge (18, 21): _graphml_edge_id =
Edge (18, 20): _graphml_edge_id =
Edge (18, 27): _graphml_edge_id =
Edge (18, 22): _graphml_edge_id =
Edge (18, 23): _graphml_edge_id =
Edge (18, 25): _graphml_edge_id =
Edge (18, 26): _graphml_edge_id =
Edge (18, 28): _graphml_edge_id =
Edge (18, 29): _graphml_edge_id =
Edge (18, 30): _graphml_edge_id =
Edge (18, 31): _graphml_edge_id =
Edge (19, 23): _graphml_edge_id =
Edge (19, 21): _graphml_edge_id =
Edge (19, 24): _graphml_edge_id =
Edge (19, 26): _graphml_edge_id =
Edge (19, 20): _graphml_edge_id =
Edge (19, 22): _graphml_edge_id =
Edge (19, 25): _graphml_edge_id =
Edge (19, 28): _graphml_edge_id =
Edge (19, 27): _graphml_edge_id =
Edge (19, 29): _graphml_edge_id =
Edge (19, 30): _graphml_edge_id =
Edge (20, 23): _graphml_edge_id =
Edge (20, 27): _graphml_edge_id =
Edge (20, 24): _graphml_edge_id =
Edge (20, 21): _graphml_edge_id =
Edge (20, 22): _graphml_edge_id =
Edge (20, 25): _graphml_edge_id =
Edge (20, 29): _graphml_edge_id =
Edge (20, 28): _graphml_edge_id =
Edge (20, 26): _graphml_edge_id =
Edge (20, 30): _graphml_edge_id =
Edge (21, 23): _graphml_edge_id =
Edge (21, 26): _graphml_edge_id =
Edge (21, 24): _graphml_edge_id =
Edge (21, 25): _graphml_edge_id =
Edge (21, 22): _graphml_edge_id =
Edge (21, 28): _graphml_edge_id =
Edge (21, 27): _graphml_edge_id =
Edge (21, 29): _graphml_edge_id =
Edge (21, 30): _graphml_edge_id =
Edge (22, 28): _graphml_edge_id =
Edge (22, 25): _graphml_edge_id =
Edge (22, 23): _graphml_edge_id =
Edge (22, 26): _graphml_edge_id =
Edge (22, 24): _graphml_edge_id =
Edge (22, 27): _graphml_edge_id =
Edge (22, 30): _graphml_edge_id =
Edge (22, 29): _graphml_edge_id =
Edge (23, 24): _graphml_edge_id =
Edge (23, 26): _graphml_edge_id =
Edge (23, 25): _graphml_edge_id =
Edge (23, 28): _graphml_edge_id =
Edge (23, 27): _graphml_edge_id =
Edge (23, 29): _graphml_edge_id =
Edge (23, 30): _graphml_edge_id =
Edge (23, 31): _graphml_edge_id =
Edge (24, 26): _graphml_edge_id =
Edge (24, 25): _graphml_edge_id =
Edge (24, 28): _graphml_edge_id =
Edge (24, 27): _graphml_edge_id =
Edge (24, 29): _graphml_edge_id =
Edge (24, 30): _graphml_edge_id =
Edge (24, 31): _graphml_edge_id =
Edge (25, 28): _graphml_edge_id =
Edge (25, 26): _graphml_edge_id =
Edge (25, 27): _graphml_edge_id =
Edge (25, 29): _graphml_edge_id =
Edge (25, 30): _graphml_edge_id =
Edge (26, 28): _graphml_edge_id =
Edge (26, 27): _graphml_edge_id =
Edge (26, 29): _graphml_edge_id =
Edge (26, 30): _graphml_edge_id =
Edge (27, 28): _graphml_edge_id =
Edge (27, 29): _graphml_edge_id =
Edge (27, 30): _graphml_edge_id =
Edge (27, 31): _graphml_edge_id =
Edge (28, 29): _graphml_edge_id =
Edge (28, 30): _graphml_edge_id =
Edge (29, 30): _graphml_edge_id =
Edge (30, 31): _graphml_edge_id =
Property: weight
Edge (0, 1): weight = 22810
Edge (0, 2): weight = 21940
Edge (0, 3): weight = 19057
Edge (0, 5): weight = 12050
Edge (0, 6): weight = 11696
Edge (0, 4): weight = 11455
Edge (0, 7): weight = 8891
Edge (0, 9): weight = 7019
Edge (0, 8): weight = 6312
Edge (0, 11): weight = 5753
Edge (0, 10): weight = 5208
Edge (0, 12): weight = 5069
Edge (0, 13): weight = 4528
Edge (0, 14): weight = 4502
Edge (0, 15): weight = 4375
Edge (0, 16): weight = 3641
Edge (0, 17): weight = 2754
Edge (0, 18): weight = 2738
Edge (0, 19): weight = 2647
Edge (0, 21): weight = 1974
Edge (0, 20): weight = 1916
Edge (0, 22): weight = 1390
Edge (0, 23): weight = 1373
Edge (0, 25): weight = 1236
Edge (0, 24): weight = 1205
Edge (0, 26): weight = 1124
Edge (0, 27): weight = 1093
Edge (0, 28): weight = 877
Edge (0, 29): weight = 368
Edge (0, 30): weight = 358
Edge (0, 31): weight = 17
Edge (1, 2): weight = 19428
Edge (1, 3): weight = 17790
Edge (1, 4): weight = 10514
Edge (1, 5): weight = 10351
Edge (1, 6): weight = 9786
Edge (1, 7): weight = 7624
Edge (1, 8): weight = 5762
Edge (1, 9): weight = 5318
Edge (1, 11): weight = 5144
Edge (1, 10): weight = 4916
Edge (1, 12): weight = 4334
Edge (1, 14): weight = 3871
Edge (1, 13): weight = 3833
Edge (1, 15): weight = 3423
Edge (1, 18): weight = 2824
Edge (1, 16): weight = 2799
Edge (1, 17): weight = 2738
Edge (1, 19): weight = 2545
Edge (1, 20): weight = 1684
Edge (1, 21): weight = 1659
Edge (1, 24): weight = 1358
Edge (1, 23): weight = 1241
Edge (1, 22): weight = 1228
Edge (1, 25): weight = 1059
Edge (1, 26): weight = 891
Edge (1, 27): weight = 866
Edge (1, 28): weight = 806
Edge (1, 29): weight = 365
Edge (1, 30): weight = 333
Edge (1, 31): weight = 5
Edge (2, 3): weight = 22510
Edge (2, 4): weight = 14925
Edge (2, 5): weight = 11387
Edge (2, 7): weight = 10005
Edge (2, 8): weight = 8331
Edge (2, 6): weight = 8019
Edge (2, 10): weight = 6611
Edge (2, 11): weight = 6580
Edge (2, 12): weight = 5661
Edge (2, 9): weight = 5097
Edge (2, 13): weight = 4862
Edge (2, 15): weight = 4311
Edge (2, 14): weight = 3940
Edge (2, 17): weight = 3556
Edge (2, 16): weight = 2843
Edge (2, 18): weight = 2278
Edge (2, 19): weight = 2094
Edge (2, 21): weight = 2016
Edge (2, 20): weight = 1476
Edge (2, 24): weight = 1283
Edge (2, 22): weight = 1154
Edge (2, 25): weight = 1085
Edge (2, 23): weight = 1065
Edge (2, 26): weight = 1063
Edge (2, 27): weight = 987
Edge (2, 28): weight = 774
Edge (2, 29): weight = 329
Edge (2, 30): weight = 250
Edge (2, 31): weight = 6
Edge (3, 4): weight = 10911
Edge (3, 5): weight = 10675
Edge (3, 7): weight = 8296
Edge (3, 6): weight = 6615
Edge (3, 8): weight = 5525
Edge (3, 10): weight = 5222
Edge (3, 11): weight = 5180
Edge (3, 9): weight = 5018

In [100]:
g = nx.Graph()
edgelist = [('it', 'fr', {'weight': 2}), ]
# set edgelist
g.add_edges_from(edgelist)